(() => {
  document.documentElement.classList.add('js-running');
  const NS='http://www.w3.org/2000/svg';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const COLORS={control:'#42e8e0',compute:'#3185fc',edge:'#ff9f43',ai:'#9b6cff',agent:'#dffe02',data:'#40e68b',dev:'#55a8ff',ops:'#ff5d73',network:'#3185fc',cloud:'#a5b7cc'};
  const lensDefs={
    physical:{label:'PHYSICAL',cats:['compute','control','edge','network','cloud'],tags:['physical']},
    ai:{label:'AI',cats:['ai','agent','data','compute'],tags:['ai']},
    network:{label:'NETWORK',cats:['network','cloud','compute','control','edge'],tags:['network']},
    data:{label:'DATA',cats:['data','ai','agent','dev'],tags:['data']},
    security:{label:'SECURITY',cats:['network','ops','dev','cloud'],tags:['security']},
    mission:{label:'MISSION',cats:[],tags:[]}, software:{label:'SOFTWARE',cats:['control','compute','dev','ops','agent'],tags:['software']},
    performance:{label:'PERFORMANCE',cats:['compute','ai','ops'],tags:['performance']}, cost:{label:'COST',cats:['compute','cloud','ai'],tags:['cost']}, learning:{label:'LEARNING',cats:[],tags:['learning']}
  };
  const districts=[
    {id:'cloud',name:'Cloud Orbit',icon:'☁️',sub:'APIs · GitHub · SaaS · GPU cloud',x:540,y:30,w:520,h:160,tags:['network','security','cost']},
    {id:'network',name:'Perimeter Gate',icon:'🌐',sub:'LAN · Router · DNS · HTTPS · Remote',x:615,y:205,w:370,h:160,tags:['network','security','physical']},
    {id:'control',name:'Control Deck',icon:'🎛️',sub:'Human · UI · IDE · terminal',x:70,y:390,w:340,h:190,tags:['physical','software']},
    {id:'compute',name:'Compute Foundry',icon:'🏭',sub:'Hosts · CPU · GPU · runtime',x:470,y:385,w:450,h:210,tags:['physical','performance','cost','software']},
    {id:'edge',name:'Edge Yard',icon:'📡',sub:'Pi · IoT · field compute',x:1160,y:395,w:340,h:180,tags:['physical','network']},
    {id:'ai',name:'AI Reactor',icon:'⚛️',sub:'Models · inference · embeddings',x:520,y:650,w:420,h:195,tags:['ai','performance','cost']},
    {id:'agent',name:'Agent Operations',icon:'🤖',sub:'Loops · tools · MCP · workflow',x:960,y:645,w:390,h:205,tags:['ai','software','data']},
    {id:'data',name:'Data Vault',icon:'💾',sub:'Corpus · vectors · DB · cache',x:80,y:640,w:390,h:205,tags:['data','ai','security']},
    {id:'dev',name:'Dev Dock',icon:'🧑‍💻',sub:'Git · CI/CD · deploy',x:80,y:70,w:390,h:205,tags:['software','security','data']},
    {id:'ops',name:'Ops Tower',icon:'📊',sub:'Observability · secrets · backup',x:1180,y:70,w:330,h:205,tags:['security','performance','software']}
  ];
  const nodeSeeds={
    control:[['user','User','👤','human intent'],['chat','Chat Interface','💬','conversation UI'],['ide','IDE / Coding Agent','🧑‍💻','build with AI'],['shell','Terminal / Shell','⌨️','direct machine control'],['browser','Browser','🌐','web interface'],['repo','Source Repository','📁','project history']],
    network:[['lan','LAN','🏠','local network'],['router','Router / Gateway','📡','moves traffic'],['dns','DNS','📖','name → address'],['proxy','Reverse Proxy','🚦','routes web requests'],['tls','TLS / HTTPS','🔐','encrypts transport'],['remote','Secure Remote Access','🛰️','reach home safely']],
    compute:[['host','Host Machine','🖥️','physical computer'],['cpu','CPU','🧮','general compute'],['gpu','GPU / Accelerator','🎮','parallel compute'],['ram','RAM','🧠','working memory'],['storage','Persistent Storage','💽','keeps data'],['runtime','Container Runtime','🐳','isolated services']],
    edge:[['edgeNode','Edge Node','🥧','small always-on compute'],['iot','IoT Device','📟','sensors / actuators'],['mqtt','Message Bus','📨','device events']],
    ai:[['model','Model','🧠','learned behavior'],['weights','Model Weights','🏋️','learned parameters'],['inference','Inference Engine','⚡','executes model'],['modelServer','Model Server / API','📡','serves inference'],['tokenizer','Tokenizer + Context','🪙','text ↔ tokens'],['embedding','Embedding Model','🔢','meaning → vectors']],
    data:[['corpus','Corpus / Files','📚','source knowledge'],['chunker','Parser + Chunker','✂️','prepare documents'],['vector','Vector Store','🔢','similarity memory'],['retriever','Retriever / Search','🔎','find relevant context'],['appdb','Application Database','🗃️','structured state'],['cache','Cache / State Store','⚡','fast temporary state']],
    agent:[['agentLoop','Agent Loop','🤖','observe → decide → act'],['tool','Tool','🛠️','external action'],['mcp','MCP Interface','🔌','standard capability bridge'],['memory','Agent Memory','🧠','persistent context'],['workflow','Workflow Engine','🏭','repeatable automation'],['queue','Queue / Event','📨','asynchronous work']],
    dev:[['git','Git','🌿','local version control'],['github','Remote Source Control','🐙','shared repository'],['cicd','CI / CD','⚙️','test / build / deploy'],['artifact','Build Artifact','📦','shippable output']],
    ops:[['secrets','Identity + Secrets','🔑','credentials / access'],['firewall','Trust Boundary / Firewall','🛡️','controls exposure'],['observe','Observability','📡','logs · metrics · traces'],['backup','Backup + Recovery','💿','restore state']],
    cloud:[['cloudAi','Cloud AI API','☁️','remote models'],['publicApi','Public API / Data','🌍','external capabilities'],['gpuCloud','GPU Cloud','🧊','rented accelerators'],['saas','SaaS','🧰','hosted services']]
  };
  const roles={
    user:{eli5:'You provide the goal. Every AI system ultimately exists to turn human intent into useful work.',why:'Starts the system',in:'Goal / question',out:'Intent',unlocks:'Every mission',tags:['physical','learning']},
    model:{eli5:'The learned brain. It predicts useful outputs from the context it receives.',why:'Generate or classify',in:'Tokens / context',out:'Probabilities / tokens',unlocks:'Chat, coding, agents',tags:['ai','performance','cost'],prereq:['tokenizer'],next:['inference','modelServer','agentLoop']},
    inference:{eli5:'The engine that actually runs model math on CPU/GPU hardware.',why:'Execute the model',in:'Weights + tokens',out:'Model computation',unlocks:'Local AI',tags:['ai','performance'],prereq:['model','weights','cpu','gpu'],next:['modelServer']},
    modelServer:{eli5:'Turns inference into a service other apps can call.',why:'Expose models to apps',in:'API request',out:'Model response',unlocks:'Chat apps, RAG, agents',tags:['ai','network','software'],aliases:['ollama','run llm locally','local inference','llm api','serve model'],prereq:['inference','model'],next:['chat','agentLoop','retriever'],implementations:[
      {name:'Ollama',role:'Simple local model serving',complexity:'Low',scale:'Personal / small server',hardware:'CPU/GPU local',ideal:'Fast local setup',tradeoff:'Less serving control than dedicated high-throughput stacks',source:'https://docs.ollama.com/api/introduction'},
      {name:'llama.cpp',role:'Low-level local inference + server',complexity:'Medium',scale:'Device → workstation',hardware:'Broad CPU/GPU support',ideal:'Maximum local/runtime control',tradeoff:'More hands-on configuration',source:'https://github.com/ggml-org/llama.cpp'},
      {name:'vLLM',role:'High-throughput model serving',complexity:'Higher',scale:'Server / multi-GPU',hardware:'GPU-oriented',ideal:'Serving many requests',tradeoff:'Heavier operational footprint',source:'https://docs.vllm.ai/en/latest/'}]},
    embedding:{eli5:'Turns meaning into coordinates so similar things end up near each other mathematically.',why:'Semantic search',in:'Text / data',out:'Vector',unlocks:'RAG and similarity search',tags:['ai','data'],prereq:['model'],next:['vector','retriever'],implementations:[{name:'sentence-transformers',role:'Local embedding models',complexity:'Low–Medium',scale:'Laptop → server',hardware:'CPU or GPU',ideal:'Self-hosted semantic search',tradeoff:'Model choice matters; quality varies by domain',source:'https://sbert.net/'}]},
    vector:{eli5:'A searchable warehouse for embeddings. Ask for “things most like this” and it finds nearby vectors mathematically.',why:'Similarity retrieval',in:'Vectors',out:'Nearest matches',unlocks:'RAG, semantic memory',tags:['data','ai'],aliases:['vector db','vector database','vector store','qdrant'],prereq:['embedding'],next:['retriever'],implementations:[{name:'Qdrant',role:'Vector search database',complexity:'Medium',scale:'Local → server',hardware:'CPU/RAM/storage',ideal:'Dedicated vector retrieval',tradeoff:'Adds another service',source:'https://qdrant.tech/documentation/overview/vector-search/'},{name:'Chroma',role:'Embedded vector store',complexity:'Low',scale:'Prototype → small app',hardware:'In-process',ideal:'Getting RAG working fast',tradeoff:'Less suited to heavy multi-service load',source:'https://docs.trychroma.com/'},{name:'pgvector',role:'Vectors inside PostgreSQL',complexity:'Medium',scale:'With your existing DB',hardware:'Your Postgres host',ideal:'One database for rows and vectors',tradeoff:'Tuning lives inside Postgres ops',source:'https://github.com/pgvector/pgvector'}]},
    retriever:{eli5:'The librarian. It searches your knowledge and hands the model only the useful pieces.',why:'Find useful context',in:'Question / vector',out:'Relevant chunks',unlocks:'RAG',tags:['data','ai'],aliases:['rag search','retrieval'],prereq:['corpus','chunker','embedding','vector'],next:['model'],implementations:[{name:'LlamaIndex',role:'RAG framework',complexity:'Medium',scale:'Prototype → production',hardware:'App-level',ideal:'Document ingestion + retrieval pipelines',tradeoff:'Framework abstractions to learn',source:'https://docs.llamaindex.ai/'},{name:'LangChain',role:'LLM app framework with retrievers',complexity:'Medium',scale:'Prototype → production',hardware:'App-level',ideal:'Composable chains around retrieval',tradeoff:'Fast-moving API surface',source:'https://python.langchain.com/docs/concepts/retrievers/'}]},
    mcp:{eli5:'A standard connection layer that lets AI applications discover and use external tools and resources.',why:'Connect AI to capabilities',in:'Tool/resource request',out:'Structured result',unlocks:'Portable AI integrations',tags:['ai','network','software','security'],aliases:['model context protocol','ai tools','connect ai to github','mcp server'],prereq:['tool'],next:['agentLoop'],implementations:[{name:'MCP',role:'Host/client/server protocol',complexity:'Medium',scale:'Local or remote',hardware:'Any host',ideal:'Standard AI-tool integrations',tradeoff:'Security and permission design matter',source:'https://modelcontextprotocol.io/docs/2026-07-28/learn/architecture'}]},
    agentLoop:{eli5:'A model that repeatedly looks at the situation, chooses an action, uses a tool, observes the result, and continues.',why:'Multi-step work',in:'Goal + observations',out:'Actions + final result',unlocks:'Autonomous workflows',tags:['ai','software','data'],aliases:['agent','ai agent','autonomous agent'],prereq:['model','tool'],next:['memory','mcp','workflow'],implementations:[{name:'Claude Agent SDK',role:'Agent loop framework',complexity:'Medium',scale:'Script → production agents',hardware:'App-level + API',ideal:'Tool-using agents with strong model reasoning',tradeoff:'Anchored to one model provider',source:'https://docs.claude.com/en/api/agent-sdk/overview'},{name:'LangGraph',role:'Graph-based agent orchestration',complexity:'Medium–High',scale:'Prototype → production',hardware:'App-level',ideal:'Explicit control over agent state machines',tradeoff:'More upfront structure to design',source:'https://langchain-ai.github.io/langgraph/'}]},
    tool:{eli5:'A capability the AI can invoke, such as reading a file, running code, browsing, or calling an API.',why:'Let AI act',in:'Structured arguments',out:'Tool result',unlocks:'Tool-using AI and agents',tags:['ai','software','security'],prereq:['model'],next:['mcp','agentLoop']},
    runtime:{eli5:'Runs applications in isolated containers so services can be packaged, moved, restarted and connected predictably.',why:'Package services',in:'Image + config',out:'Running container',unlocks:'Repeatable homelab services',tags:['physical','software','security'],aliases:['docker','containers','container runtime'],next:['modelServer','observe'],implementations:[{name:'Docker',role:'Container engine + tooling',complexity:'Low–Medium',scale:'Laptop → server',hardware:'Host OS',ideal:'Self-hosted services',tradeoff:'Adds container/network/storage concepts',source:'https://docs.docker.com/engine/'}]},
    dns:{eli5:'The internet phonebook. It converts human-readable names into network addresses.',why:'Find services by name',in:'Hostname',out:'IP address',unlocks:'Reliable service naming',tags:['network','learning'],next:['proxy','tls'],implementations:[{name:'Pi-hole',role:'Local DNS + ad blocking',complexity:'Low',scale:'Home network',hardware:'Pi / tiny service',ideal:'Network-wide filtering + local names',tradeoff:'Becomes critical infrastructure once adopted',source:'https://docs.pi-hole.net/'},{name:'AdGuard Home',role:'Local DNS + filtering',complexity:'Low',scale:'Home network',hardware:'Pi / tiny service',ideal:'Similar goals with built-in DoH/DoT',tradeoff:'Same single-point-of-failure caution',source:'https://github.com/AdguardTeam/AdGuardHome/wiki'}]},
    proxy:{eli5:'A traffic director. One public doorway can route different web requests to the correct internal service.',why:'Route inbound web traffic',in:'HTTP request',out:'Request to service',unlocks:'Clean URLs + centralized HTTPS',tags:['network','security'],aliases:['reverse proxy','caddy'],prereq:['dns'],next:['tls'],implementations:[{name:'Caddy',role:'Reverse proxy with automatic HTTPS',complexity:'Low',scale:'Home → production',hardware:'Small service',ideal:'Simple secure publishing',tradeoff:'Still requires exposure/access decisions',source:'https://caddyserver.com/docs/quick-starts/reverse-proxy'}]},
    remote:{eli5:'Creates a private encrypted path back to your devices without exposing every service directly to the public internet.',why:'Reach home securely',in:'Authenticated device traffic',out:'Encrypted private connection',unlocks:'Remote homelab access',tags:['network','security'],aliases:['tailscale','vpn','remote access'],implementations:[{name:'Tailscale',role:'Encrypted mesh networking',complexity:'Low',scale:'Personal → team',hardware:'Client on each node',ideal:'Remote homelab access',tradeoff:'Introduces identity/control-plane dependency',source:'https://tailscale.com/kb/'}]},
    observe:{eli5:'Your system’s senses. Metrics show how much, logs show what happened, traces show where requests traveled.',why:'Understand system behavior',in:'Telemetry',out:'Metrics / logs / traces',unlocks:'Troubleshooting and performance work',tags:['security','performance','software'],aliases:['observability','monitoring','otel','opentelemetry'],implementations:[{name:'OpenTelemetry',role:'Telemetry instrumentation standard',complexity:'Medium',scale:'Single service → distributed systems',hardware:'App/collector resources',ideal:'Vendor-neutral telemetry',tradeoff:'Collection is not the same as storage/visualization',source:'https://opentelemetry.io/docs/concepts/signals/'},{name:'Prometheus',role:'Metrics collection + alerting',complexity:'Medium',scale:'Homelab → production',hardware:'Modest server',ideal:'Pull-based metrics with a query language',tradeoff:'Metrics only; logs/traces need companions',source:'https://prometheus.io/docs/'},{name:'Grafana',role:'Dashboards + visualization',complexity:'Low–Medium',scale:'Homelab → production',hardware:'Small service',ideal:'One pane of glass over many sources',tradeoff:'Dashboards need gardening to stay honest',source:'https://grafana.com/docs/'}]},
    github:{eli5:'A remote home for Git repositories where code collaboration, review and automation can happen.',why:'Share and coordinate code',in:'Commits / pull requests',out:'Repository state',unlocks:'Collaboration + CI/CD',tags:['software','network','security'],aliases:['github','remote repo'],next:['cicd'],implementations:[{name:'GitHub',role:'Hosted collaboration platform',complexity:'Low',scale:'Solo → enterprise',hardware:'None (SaaS)',ideal:'Default home for open + private code',tradeoff:'Your workflow lives on someone else\'s platform',source:'https://docs.github.com/'},{name:'Forgejo',role:'Self-hosted Git forge',complexity:'Medium',scale:'Personal → team',hardware:'Small service',ideal:'Owning your forge in the homelab',tradeoff:'You operate what GitHub operates for you',source:'https://forgejo.org/docs/'}]},
    cicd:{eli5:'An automated assembly line that tests, builds and deploys code when repository events happen.',why:'Automate delivery',in:'Code change',out:'Tests / build / deployment',unlocks:'Repeatable shipping',tags:['software','security'],aliases:['github actions','ci cd','pipeline'],prereq:['git','github'],next:['artifact'],implementations:[{name:'GitHub Actions',role:'Hosted CI/CD',complexity:'Low–Medium',scale:'Solo → enterprise',hardware:'Hosted or self-hosted runners',ideal:'CI living next to the repo',tradeoff:'YAML sprawl; runner minutes cost at scale',source:'https://docs.github.com/actions'},{name:'GitLab CI',role:'Integrated CI/CD',complexity:'Medium',scale:'Solo → enterprise',hardware:'Hosted or self-managed',ideal:'Single-platform repo + pipeline + registry',tradeoff:'Heavier platform to self-host',source:'https://docs.gitlab.com/ee/ci/'}]},
    gpu:{eli5:'A massively parallel calculator. AI workloads use it to perform many matrix operations at once.',why:'Accelerate AI math',in:'Model operations',out:'Fast parallel compute',unlocks:'Faster/larger local models',tags:['physical','performance','cost'],aliases:['vram','graphics card','accelerator'],next:['inference'],implementations:[{name:'CUDA',role:'NVIDIA GPU compute stack',complexity:'Medium',scale:'Laptop → datacenter',hardware:'NVIDIA GPUs',ideal:'Broadest AI framework support',tradeoff:'Vendor lock-in',source:'https://docs.nvidia.com/cuda/'},{name:'ROCm',role:'AMD GPU compute stack',complexity:'Medium–High',scale:'Workstation → server',hardware:'AMD GPUs',ideal:'Open-source stack on AMD hardware',tradeoff:'Narrower official support matrix',source:'https://rocm.docs.amd.com/'}]},
    ram:{eli5:'Fast temporary working space used by the operating system, services, model weights and caches.',why:'Hold active data',in:'Active program data',out:'Fast memory access',unlocks:'Larger workloads',tags:['physical','performance','cost']},
    edgeNode:{eli5:'A small computer that stays close to devices or services and can run lightweight always-on jobs.',why:'Always-on edge work',in:'Events / local tasks',out:'Services / control',unlocks:'IoT, monitoring, automation',tags:['physical','network'],aliases:['raspberry pi','pi','edge compute'],implementations:[{name:'Raspberry Pi',role:'Small always-on computer',complexity:'Low',scale:'Single device → fleet',hardware:'ARM SBC',ideal:'Cheap 24/7 services and device bridges',tradeoff:'Limited compute; SD-card wear without care',source:'https://www.raspberrypi.com/documentation/'}]},
    chat:{eli5:'The conversation surface. It turns a model API into something a person can actually talk to.',why:'Human-friendly AI access',in:'User messages',out:'Model responses',unlocks:'Daily-driver local AI',tags:['software','ai'],implementations:[{name:'Open WebUI',role:'Self-hosted chat interface',complexity:'Low',scale:'Personal → team',hardware:'Small service',ideal:'Chat UI over local model servers',tradeoff:'Another service to run and update',source:'https://docs.openwebui.com/'}]},
    appdb:{eli5:'Structured, durable memory for applications. Rows, relations, and transactions instead of loose files.',why:'Reliable structured state',in:'Queries / writes',out:'Consistent data',unlocks:'Stateful applications',tags:['data','software'],implementations:[{name:'PostgreSQL',role:'Relational database',complexity:'Medium',scale:'Single node → clustered',hardware:'CPU/RAM/storage',ideal:'General-purpose application data',tradeoff:'Operational care: backups, tuning, upgrades',source:'https://www.postgresql.org/docs/'},{name:'SQLite',role:'Embedded file database',complexity:'Low',scale:'Single process',hardware:'Any',ideal:'Local apps and small services',tradeoff:'Single-writer; not built for many concurrent services',source:'https://sqlite.org/docs.html'}]},
    cache:{eli5:'Very fast short-term memory. Keeps hot data close so systems stop recomputing or refetching it.',why:'Speed + temporary state',in:'Keys / values',out:'Microsecond reads',unlocks:'Fast apps, sessions, queues',tags:['data','performance'],implementations:[{name:'Redis',role:'In-memory data store',complexity:'Low–Medium',scale:'Single node → clustered',hardware:'RAM-heavy',ideal:'Cache, sessions, queues, pub/sub',tradeoff:'Working set sized to RAM',source:'https://redis.io/docs/latest/'},{name:'Valkey',role:'Open-governance Redis-compatible store',complexity:'Low–Medium',scale:'Single node → clustered',hardware:'RAM-heavy',ideal:'Drop-in open-source alternative',tradeoff:'Younger ecosystem',source:'https://valkey.io/docs/'}]},
    workflow:{eli5:'A factory line for repeatable automation: triggers, steps, retries, and connections between services.',why:'Repeatable automation',in:'Trigger / event',out:'Executed steps',unlocks:'Hands-off pipelines',tags:['software','ai'],aliases:['n8n','automation'],implementations:[{name:'n8n',role:'Visual workflow automation',complexity:'Low–Medium',scale:'Personal → team',hardware:'Small service',ideal:'Connecting APIs, AI steps, and homelab services',tradeoff:'Complex logic can outgrow visual flows',source:'https://docs.n8n.io/'},{name:'Apache Airflow',role:'Code-first orchestration',complexity:'Higher',scale:'Team → data platforms',hardware:'Server-class',ideal:'Scheduled data/ML pipelines as code',tradeoff:'Heavy for simple automations',source:'https://airflow.apache.org/docs/'}]},
    queue:{eli5:'A waiting line for work. Producers drop messages, consumers process them when ready — nothing is lost in between.',why:'Decouple + absorb bursts',in:'Messages / events',out:'Reliable delivery',unlocks:'Async, resilient systems',tags:['software','data'],implementations:[{name:'NATS',role:'Lightweight messaging system',complexity:'Low–Medium',scale:'Edge → distributed',hardware:'Tiny footprint',ideal:'Simple fast pub/sub and queues',tradeoff:'Fewer heavyweight broker features',source:'https://docs.nats.io/'},{name:'RabbitMQ',role:'Full-featured message broker',complexity:'Medium',scale:'Single node → clustered',hardware:'Modest server',ideal:'Routing, acknowledgements, work queues',tradeoff:'More concepts to operate correctly',source:'https://www.rabbitmq.com/docs'}]},
    secrets:{eli5:'The locked drawer for credentials. Services get the keys they need without keys living in code or configs.',why:'Protect credentials',in:'Auth requests',out:'Scoped secrets',unlocks:'Safe automation + deploys',tags:['security','software'],implementations:[{name:'Vaultwarden',role:'Self-hosted password manager server',complexity:'Low',scale:'Personal → small team',hardware:'Tiny service',ideal:'Human credentials in the homelab',tradeoff:'Unofficial server reimplementation; track upstream',source:'https://github.com/dani-garcia/vaultwarden/wiki'},{name:'HashiCorp Vault',role:'Machine secrets management',complexity:'Higher',scale:'Team → enterprise',hardware:'Dedicated service',ideal:'Dynamic secrets for services and CI',tradeoff:'Real operational overhead (sealing, policies)',source:'https://developer.hashicorp.com/vault/docs'}]},
    firewall:{eli5:'The bouncer at every door. Decides which traffic may enter, leave, or cross between network zones.',why:'Control exposure',in:'All traffic',out:'Allowed traffic only',unlocks:'Segmented, safer networks',tags:['security','network'],implementations:[{name:'OPNsense',role:'Open-source firewall/router OS',complexity:'Medium',scale:'Home → small business',hardware:'Dedicated box / VM',ideal:'Serious homelab perimeter + VLANs',tradeoff:'Networking knowledge required',source:'https://docs.opnsense.org/'}]},
    backup:{eli5:'Time travel for your data. Regular snapshots stored elsewhere so mistakes and failures are reversible.',why:'Survive failure',in:'Live data',out:'Restorable snapshots',unlocks:'Fearless experimentation',tags:['security','data'],implementations:[{name:'restic',role:'Encrypted deduplicating backup',complexity:'Low–Medium',scale:'Laptop → servers',hardware:'Any + remote storage',ideal:'Scripted encrypted backups to many backends',tradeoff:'CLI-first; scheduling is on you',source:'https://restic.readthedocs.io/'},{name:'BorgBackup',role:'Deduplicating archive backup',complexity:'Medium',scale:'Laptop → servers',hardware:'Any + SSH target',ideal:'Space-efficient versioned archives',tradeoff:'Repo format needs Borg on both ends',source:'https://borgbackup.readthedocs.io/'}]},
    tls:{eli5:'The sealed envelope for the web. Encrypts traffic so networks in between can route it but not read it.',why:'Private transport',in:'Plain connection',out:'Encrypted channel',unlocks:'Trustworthy remote access',tags:['security','network'],implementations:[{name:"Let's Encrypt",role:'Free automated certificates',complexity:'Low',scale:'Any public site',hardware:'None (CA service)',ideal:'Auto-renewed HTTPS everywhere',tradeoff:'Requires a domain + renewal automation',source:'https://letsencrypt.org/docs/'}]},
    iot:{eli5:'The physical senses and hands of your lab: sensors that report and switches that act.',why:'Bridge digital ↔ physical',in:'Physical signals',out:'Events / actions',unlocks:'Automation of real space',tags:['physical','network'],implementations:[{name:'Home Assistant',role:'Home automation hub',complexity:'Low–Medium',scale:'Home',hardware:'Pi / small box',ideal:'Unifying devices + automations locally',tradeoff:'Integration sprawl needs curation',source:'https://www.home-assistant.io/docs/'}]},
    mqtt:{eli5:'A tiny post office for devices. Everything publishes to topics; anything interested subscribes.',why:'Lightweight device messaging',in:'Topic messages',out:'Fan-out delivery',unlocks:'IoT event pipelines',tags:['network','data'],implementations:[{name:'Eclipse Mosquitto',role:'MQTT broker',complexity:'Low',scale:'Home → industrial edge',hardware:'Tiny footprint',ideal:'Standard homelab device bus',tradeoff:'Plain broker; auth/TLS config is manual',source:'https://mosquitto.org/documentation/'}]}
  };
  const generic=(id,name,role,cat)=>({id,name,role,cat,eli5:`${name} is the ${role} layer in this system.`,why:role,in:'Upstream input',out:'Downstream result',unlocks:'Adjacent capabilities',tags:[cat==='ai'||cat==='agent'?'ai':cat==='data'?'data':cat==='network'||cat==='cloud'?'network':'software']});
  const nodes=[];
  districts.forEach(d=>{
    const list=nodeSeeds[d.id]||[];
    list.forEach((s,i)=>{
      const cols=list.length>=5?3:(list.length===4?2:Math.min(3,list.length)), row=Math.floor(i/cols), col=i%cols, pad=14, gap=8, nw=(d.w-pad*2-(cols-1)*gap)/cols, nh=42;
      const x=d.x+pad+col*(nw+gap), y=d.y+58+row*(nh+7);
      const base=generic(s[0],s[1],s[3],d.id); Object.assign(base,{icon:s[2],district:d.id,x,y,w:nw,h:nh});
      if(roles[s[0]]) Object.assign(base,roles[s[0]]);
      nodes.push(base);
    });
  });
  const byId=Object.fromEntries(nodes.map(n=>[n.id,n]));
  const districtById=Object.fromEntries(districts.map(d=>[d.id,d]));
  const edges=[
    ['user','chat','calls'],['user','ide','calls'],['ide','repo','reads'],['ide','modelServer','calls'],['chat','modelServer','calls'],['modelServer','inference','executes'],['inference','model','executes'],['model','weights','depends'],['inference','gpu','executes'],['inference','cpu','executes'],['modelServer','lan','network'],['lan','router','network'],['router','remote','network'],['router','proxy','network'],['proxy','tls','security'],['proxy','modelServer','network'],['repo','git','reads'],['git','github','data'],['github','cicd','calls'],['cicd','artifact','data'],['corpus','chunker','data'],['chunker','embedding','calls'],['embedding','vector','data'],['vector','retriever','data'],['retriever','model','data'],['agentLoop','model','calls'],['agentLoop','tool','calls'],['agentLoop','memory','data'],['agentLoop','mcp','calls'],['mcp','tool','calls'],['workflow','agentLoop','calls'],['queue','workflow','data'],['runtime','modelServer','executes'],['observe','modelServer','observes'],['observe','runtime','observes'],['secrets','github','security'],['firewall','proxy','security'],['remote','control','network'],['cloudAi','agentLoop','calls'],['publicApi','mcp','calls']
  ].map((e,i)=>({id:'e'+i,a:e[0],b:e[1],type:e[2]}));
  const missions=[
    {id:'chatbot',name:'01 · Local Chatbot',path:['user','chat','modelServer','inference','gpu','model']},
    {id:'coding',name:'02 · AI Coding Assistant',path:['user','ide','repo','shell','modelServer','model']},
    {id:'rag',name:'03 · Local RAG',path:['corpus','chunker','embedding','vector','retriever','modelServer','model']},
    {id:'mcp',name:'04 · MCP Agent',path:['user','agentLoop','mcp','tool','publicApi']},
    {id:'research',name:'05 · Autonomous Researcher',path:['user','agentLoop','browser','tool','memory','model']},
    {id:'automation',name:'06 · Automation Agent',path:['queue','workflow','agentLoop','tool','appdb']},
    {id:'remote',name:'07 · Secure Remote Homelab',path:['user','remote','router','proxy','tls','modelServer']},
    {id:'ship',name:'08 · Ship an Application',path:['ide','git','github','cicd','artifact','runtime']},
    {id:'cyber',name:'09 · Cyber Range',path:['user','edgeNode','lan','firewall','observe']},
    {id:'scale',name:'10 · Scale AI Inference',path:['router','proxy','modelServer','inference','gpu','observe']},
    {id:'homeauto',name:'11 · Smart Home AI',path:['iot','mqtt','edgeNode','agentLoop','tool']},
    {id:'delivery',name:'12 · Secure Delivery Chain',path:['secrets','github','cicd','artifact','runtime','observe']}
  ];
  const state={lens:'physical',depth:1,selected:null,selectedEdge:null,history:[],focus:false,trace:false,xray:false,xrayReturnDepth:null,highlightPath:[],mission:null,missionStep:-1,missionTimer:null,panX:0,panY:0,scale:1};
  const svg=$('#worldSvg'), viewport=$('#viewport'), districtLayer=$('#districtLayer'), nodesLayer=$('#nodesLayer'), edgesLayer=$('#edgesLayer'), effectsLayer=$('#effectsLayer'), trustLayer=$('#trustLayer');
  const statusKey=$('#statusKey'), inspector=$('#inspector');
  function svgEl(tag,attrs={}){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
  function districtDecor(d,g){
    const cx=d.x+d.w/2,cy=d.y+d.h/2,pad=10;
    if(d.id==='ops'){
      const maxR=Math.min(d.w,d.h)/2-pad;
      [.9,.6,.32].forEach(f=>g.appendChild(svgEl('circle',{cx,cy,r:maxR*f,class:'ops-ring','pointer-events':'none'})));
      g.appendChild(svgEl('line',{x1:cx,y1:cy,x2:cx,y2:cy-maxR,class:'radar-sweep','pointer-events':'none'}));
    } else if(d.id==='cloud'){
      const rx=d.w/2-pad,ry=d.h/2-pad*1.6;
      g.appendChild(svgEl('path',{d:`M ${cx-rx} ${cy} A ${rx} ${ry} 0 1 1 ${cx+rx} ${cy}`,class:'orbit-arc','pointer-events':'none'}));
    } else if(d.id==='control'){
      ['#ff5d73','#ff9f43','#40e68b'].forEach((c,i)=>g.appendChild(svgEl('circle',{cx:d.x+16+i*14,cy:d.y+16,r:4,fill:c,opacity:.5,'pointer-events':'none'})));
    } else if(d.id==='compute'){
      g.appendChild(svgEl('rect',{x:d.x,y:d.y,width:d.w,height:d.h,rx:22,fill:'url(#thermalGradient)',opacity:.07,'pointer-events':'none'}));
      [[d.x+10,d.y+10],[d.x+d.w-10,d.y+10],[d.x+10,d.y+d.h-10],[d.x+d.w-10,d.y+d.h-10]].forEach(([x,y])=>g.appendChild(svgEl('circle',{cx:x,cy:y,r:3,class:'rivet','pointer-events':'none'})));
    } else if(d.id==='data'){
      [10,20].forEach(inset=>g.appendChild(svgEl('rect',{x:d.x+inset,y:d.y+inset,width:d.w-inset*2,height:d.h-inset*2,rx:14,class:'vault-ring','pointer-events':'none'})));
    } else if(d.id==='agent'){
      const L=16;
      [[d.x+8,d.y+8,1,1],[d.x+d.w-8,d.y+8,-1,1],[d.x+8,d.y+d.h-8,1,-1],[d.x+d.w-8,d.y+d.h-8,-1,-1]].forEach(([x,y,sx,sy])=>g.appendChild(svgEl('path',{d:`M ${x} ${y+L*sy} V ${y} H ${x+L*sx}`,class:'reticle','pointer-events':'none'})));
    } else if(d.id==='dev'){
      const L=7;
      [[d.x+10,d.y+10],[d.x+d.w-10,d.y+10],[d.x+10,d.y+d.h-10],[d.x+d.w-10,d.y+d.h-10]].forEach(([x,y])=>g.appendChild(svgEl('path',{d:`M ${x-L} ${y} H ${x+L} M ${x} ${y-L} V ${y+L}`,class:'cropmark','pointer-events':'none'})));
    } else if(d.id==='edge'){
      g.appendChild(svgEl('rect',{x:d.x+8,y:d.y+8,width:d.w-16,height:d.h-16,rx:16,class:'fence','pointer-events':'none'}));
    }
  }
  function districtCenter(id){const d=districtById[id];return d?{x:d.x+d.w/2,y:d.y+d.h/2}:{x:800,y:450}}
  function nodeCenter(id){const n=byId[id];if(n)return{x:n.x+n.w/2,y:n.y+n.h/2}; if(districtById[id])return districtCenter(id); return{x:800,y:450}}
  function renderMini(){const mini=$('#miniLayer');mini.innerHTML='';districts.forEach(d=>{const r=svgEl('rect',{x:d.x,y:d.y,width:d.w,height:d.h,rx:18,fill:'#0e1b2e',stroke:COLORS[d.id]||'#29405a','stroke-width':5,opacity:.85});mini.appendChild(r)})}
  function visibleForLens(obj){if(state.lens==='mission'){if(state.highlightPath.length===0||state.highlightPath.includes(obj.id))return true; if(districtById[obj.id])return state.highlightPath.some(h=>byId[h]?.district===obj.id); return false} const def=lensDefs[state.lens]; if(!def)return true; return (def.cats||[]).includes(obj.district||obj.id)||(obj.tags||[]).some(t=>(def.tags||[]).includes(t));}
  function renderMap(){
    districtLayer.innerHTML='';nodesLayer.innerHTML='';edgesLayer.innerHTML='';effectsLayer.innerHTML='';trustLayer.innerHTML='';
    if(state.lens==='security'){const b=svgEl('rect',{x:45,y:375,width:1465,height:485,rx:35,class:'trust-boundary'});trustLayer.appendChild(b);const t=svgEl('text',{x:65,y:875,class:'zone-label'});t.textContent='LOCAL TRUST ZONE · TRAFFIC CROSSING THIS BOUNDARY DESERVES ATTENTION';trustLayer.appendChild(t)}
    edges.forEach(e=>{const a=nodeCenter(e.a),b=nodeCenter(e.b);const dPath=`M ${a.x} ${a.y} C ${(a.x+b.x)/2} ${a.y}, ${(a.x+b.x)/2} ${b.y}, ${b.x} ${b.y}`; const crossing=byId[e.a]?.district!==byId[e.b]?.district; const path=svgEl('path',{d:dPath,class:`edge ${e.type}${crossing?' crossing':''}`,'data-edge':e.id,markerEnd:'url(#arrow)'}); if(state.highlightPath.includes(e.a)&&state.highlightPath.includes(e.b)){path.classList.add('active');path.setAttribute('marker-end','url(#arrowActive)')} if(state.trace&&state.selected&&(e.a===state.selected||e.b===state.selected)){path.classList.add('active');path.setAttribute('marker-end','url(#arrowActive)')} edgesLayer.appendChild(path); const hit=svgEl('path',{d:dPath,class:'edge-hit',tabindex:'0',role:'button','aria-label':`${e.type}: ${byId[e.a]?.name||e.a} to ${byId[e.b]?.name||e.b}`}); hit.addEventListener('click',()=>selectEdge(e.id));hit.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();selectEdge(e.id)}}); edgesLayer.appendChild(hit)});
    districts.forEach(d=>{
      const g=svgEl('g',{class:`district district-${d.id}`,'data-id':d.id,tabindex:'0',role:'button','aria-label':`${d.name}: ${d.sub}`});
      g.style.setProperty('--accent',COLORS[d.id]||'#29405a');
      if(state.selected===d.id)g.classList.add('highlight');
      if(state.focus&&state.selected&&state.selected!==d.id&&byId[state.selected]?.district!==d.id)g.classList.add('focusdim');
      if(state.depth>0 && state.selected!==d.id && !visibleForLens({...d,district:d.id,tags:d.tags}))g.classList.add('dim');
      const r=svgEl('rect',{x:d.x,y:d.y,width:d.w,height:d.h,class:'dbase'}); if(state.depth===0)r.style.strokeWidth='4';g.appendChild(r);
      const tex=svgEl('rect',{x:d.x,y:d.y,width:d.w,height:d.h,rx:22,class:'dtex','pointer-events':'none'});g.appendChild(tex);
      districtDecor(d,g);
      const ti=svgEl('text',{x:d.x+22,y:d.y+40,class:'dicon'});ti.textContent=d.icon;g.appendChild(ti);
      const tn=svgEl('text',{x:d.x+65,y:d.y+35,class:'dname'});tn.textContent=d.name;g.appendChild(tn);
      const ts=svgEl('text',{x:d.x+65,y:d.y+55,class:'dsub'});ts.textContent=d.sub;g.appendChild(ts);
      g.addEventListener('click',()=>select(d.id));g.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();select(d.id)}});districtLayer.appendChild(g)
    });
    if(state.depth>=2){nodes.forEach(n=>{
      const g=svgEl('g',{class:'node','data-id':n.id,'data-district':n.district,tabindex:'0',role:'button','aria-label':`${n.name}: ${n.role}`});
      if(state.selected===n.id)g.classList.add('selected');
      if(n.id!==state.selected && !visibleForLens(n)&&state.lens!=='mission')g.classList.add('dim');
      if(state.lens==='mission'&&state.highlightPath.length&&n.id!==state.selected&&!state.highlightPath.includes(n.id))g.classList.add('dim');
      if(state.focus&&state.selected&&n.id!==state.selected&&!isNeighbor(state.selected,n.id))g.classList.add('focusdim');
      const r=svgEl('rect',{x:n.x,y:n.y,width:n.w,height:n.h});g.appendChild(r);
      const catBar=svgEl('rect',{x:n.x,y:n.y,width:n.w,height:3,rx:1.5,class:'ncat'});catBar.style.fill=COLORS[n.district]||'#29405a';catBar.style.opacity='.55';g.appendChild(catBar);
      const ic=svgEl('text',{x:n.x+10,y:n.y+25,class:'nicon'});ic.textContent=n.icon;g.appendChild(ic);
      const nm=svgEl('text',{x:n.x+35,y:n.y+23,class:'nname'});nm.textContent=n.name.length>22?n.name.slice(0,21)+'…':n.name;g.appendChild(nm);
      if(state.depth>=3){const rr=svgEl('text',{x:n.x+10,y:n.y+36,class:'nrole'});rr.textContent=n.role;g.appendChild(rr);}
      if(state.depth>=3){const labels=(n.implementations||[]).map(x=>x.name); labels.slice(0,2).forEach((label,i)=>{const ig=svgEl('g',{class:'impl'});const w=Math.min((n.w-23)/2,96),x=n.x+7+i*(w+5),y=n.y+n.h+5;const ir=svgEl('rect',{x,y,width:w,height:20});const it=svgEl('text',{x:x+6,y:y+13});it.textContent=label.length>15?label.slice(0,14)+'…':label;ig.setAttribute('tabindex','0');ig.setAttribute('role','button');ig.setAttribute('aria-label',`${label}, implementation of ${n.name}`);ig.append(ir,it);const openImpl=ev=>{ev.stopPropagation?.();select(n.id);openCompare(n.id)};ig.addEventListener('click',openImpl);ig.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();openImpl(ev)}});nodesLayer.appendChild(ig)})}
      g.addEventListener('click',()=>select(n.id));g.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();select(n.id)}});nodesLayer.appendChild(g)
    })}
    if(state.highlightPath.length>1)drawPackets();
    updateTransform();updateHUD();
  }
  function isNeighbor(a,b){return edges.some(e=>(e.a===a&&e.b===b)||(e.a===b&&e.b===a))||byId[b]?.district===byId[a]?.district}
  function drawPackets(){for(let i=0;i<state.highlightPath.length-1;i++){const a=nodeCenter(state.highlightPath[i]),b=nodeCenter(state.highlightPath[i+1]);const c=svgEl('circle',{r:6,class:'packet'});const motion=svgEl('animateMotion',{dur:`${1.25+i*.08}s`,repeatCount:'indefinite',path:`M${a.x},${a.y} C${(a.x+b.x)/2},${a.y} ${(a.x+b.x)/2},${b.y} ${b.x},${b.y}`});c.appendChild(motion);effectsLayer.appendChild(c)}}
  function updateTransform(){viewport.setAttribute('transform',`translate(${state.panX} ${state.panY}) scale(${state.scale})`);const v=$('#miniViewport');const vw=1600/state.scale,vh=900/state.scale;v.setAttribute('width',Math.min(1584,vw));v.setAttribute('height',Math.min(884,vh));v.setAttribute('x',Math.max(8,170-state.panX/state.scale));v.setAttribute('y',Math.max(8,120-state.panY/state.scale))}
  function updateHUD(){
    const names=['Z0 WORLD','Z1 DISTRICT','Z2 CONCEPT','Z3 IMPLEMENTATION','Z4 MECHANISM','Z5 ENGINEERING'];$('#zoomLabel').textContent=names[state.depth];
    let c=`<button data-crumb-home="1">WORLD</button> › <button data-crumb-home="1"><b>REFERENCE LAB</b></button>`;
    if(state.selected){const n=byId[state.selected],d=districtById[state.selected]||districtById[n?.district]; if(d)c+=n?` › <button data-crumb-district="${d.id}">${d.name}</button>`:` › ${d.name}`; if(n)c+=` › <b>${n.name}</b>`} $('#crumbs').innerHTML=c;
    statusKey.innerHTML=`<span>◉ CONCEPT</span><span>▣ implementation appears at Z3</span>`;
    $$('.bottom .lens[data-lens]').forEach(b=>{const on=b.dataset.lens===state.lens;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});
    const moreIds=['software','performance','cost','learning'],moreOn=moreIds.includes(state.lens);const more=$('#moreLens');more.classList.toggle('active',moreOn);more.setAttribute('aria-pressed',String(moreOn));more.textContent=moreOn?`MORE · ${lensDefs[state.lens].label}`:'MORE ▾';
  }
  function select(id){if(state.selected!==id||state.selectedEdge)state.history.push({selected:state.selected,selectedEdge:state.selectedEdge,depth:state.depth,lens:state.lens,panX:state.panX,panY:state.panY});state.selected=id;state.selectedEdge=null;state.focus=false;state.trace=false;state.xray=false; if(districtById[id]){if(state.depth<2)state.depth=2;state.scale=[.88,.96,1.02,1.08,1.13,1.18][state.depth];const d=districtById[id];state.panX=800-state.scale*(d.x+d.w/2);state.panY=450-state.scale*(d.y+d.h/2)} if(byId[id]&&state.depth<2)state.depth=2; renderMap();renderInspector(); if(innerWidth<900)inspector.classList.add('open')}
  function renderInspector(){
    if(state.selectedEdge){renderEdgeInspector();return}
    const id=state.selected;if(!id){renderWelcome();return}
    const n=byId[id]; if(!n){const d=districtById[id];$('#insEyebrow').textContent='DISTRICT';$('#insIcon').textContent=d.icon;$('#insTitle').textContent=d.name;$('#insPath').textContent=`World → ${d.name}`;$('#insBody').innerHTML=`<div class="eli5"><b>ELI5</b><p>${d.sub}. This region groups concepts that solve the same class of problem while preserving their position across every lens.</p></div><div class="section"><h3>Zoom deeper</h3><div class="chips"><button class="chip" data-go-depth="2">Z2 · reveal concepts</button><button class="chip" data-go-depth="3">Z3 · reveal implementations</button></div></div>`;renderActions(null);return}
    $('#insEyebrow').textContent='CONCEPT';$('#insIcon').textContent=n.icon;$('#insTitle').textContent=n.name;$('#insPath').textContent=`World → ${districtById[n.district].name} → ${n.name}`;
    let html=`<div class="eli5"><b>ELI5</b><p>${n.eli5}</p></div><div class="six"><div class="fact"><b>WHY?</b><span>${n.why}</span></div><div class="fact"><b>WHERE?</b><span>${districtById[n.district].name}</span></div><div class="fact"><b>IN?</b><span>${n.in}</span></div><div class="fact"><b>OUT?</b><span>${n.out}</span></div><div class="fact"><b>UNLOCKS?</b><span>${n.unlocks}</span></div><div class="fact"><b>STATUS</b><span>Reference concept</span></div></div>`;
    if(state.xray||state.depth>=4)html+=mechanismHtml(n);
    if(state.depth>=5)html+=engineeringHtml(n);
    if(n.implementations?.length){html+=`<div class="section"><h3>Reference implementations</h3><div class="chips">${n.implementations.map(i=>`<span class="chip">${i.name}</span>`).join('')}</div></div>`}
    const src=n.implementations?.find(i=>i.source)?.source;html+=`<div class="section source"><b>REFERENCE HYGIENE</b><br/>Concept layer: stable. Implementation layer: time-sensitive.<br/>Reference verification date: 2026-08-09.${src?` <a href="${src}" target="_blank" rel="noreferrer">Official source ↗</a>`:''}</div>`;
    $('#insBody').innerHTML=html;renderActions(n)
  }
  function selectEdge(eid){if(state.selectedEdge!==eid)state.history.push({selected:state.selected,selectedEdge:state.selectedEdge,depth:state.depth,lens:state.lens});state.selected=null;state.selectedEdge=eid;renderMap();renderInspector();if(innerWidth<900)inspector.classList.add('open')}
  function renderEdgeInspector(){const e=edges.find(x=>x.id===state.selectedEdge);if(!e){renderWelcome();return}const a=byId[e.a],b=byId[e.b];const labels={calls:'CALLS',data:'SENDS DATA',depends:'DEPENDS ON',executes:'EXECUTES',reads:'READS',security:'AUTH / TRUST',network:'NETWORK PATH',observes:'OBSERVES'};$('#insEyebrow').textContent='RELATIONSHIP';$('#insIcon').textContent='↗';$('#insTitle').textContent=labels[e.type]||e.type.toUpperCase();$('#insPath').textContent=`${a?.name||e.a} → ${b?.name||e.b}`;$('#insBody').innerHTML=`<div class="eli5"><b>WHAT THIS LINE MEANS</b><p><strong>${a?.name||e.a}</strong> ${relationshipPhrase(e.type)} <strong>${b?.name||e.b}</strong>. Lines are first-class reference objects, not decorative connectors.</p></div><div class="six"><div class="fact"><b>FROM</b><span>${a?.name||e.a}</span></div><div class="fact"><b>TO</b><span>${b?.name||e.b}</span></div><div class="fact"><b>TYPE</b><span>${labels[e.type]||e.type}</span></div><div class="fact"><b>LENS</b><span>${lensDefs[state.lens].label}</span></div></div><div class="section"><h3>Visual grammar</h3><div class="chips"><span class="chip">solid = call/control</span><span class="chip">dashed = data/trust</span><span class="chip">blue = network</span><span class="chip">cyan dash-dot = observes</span></div></div>`;renderActions(null)}
  function relationshipPhrase(type){return({calls:'calls',data:'sends data to',depends:'depends on',executes:'executes work on',reads:'reads from',security:'crosses a security/auth boundary toward',network:'routes network traffic through',observes:'collects telemetry from'})[type]||'connects to'}
  function mechanismHtml(n){let text='Trace the upstream inputs, execution step, and downstream outputs on the map.';if(n.id==='mcp')text='AI Host → MCP Client → protocol exchange → MCP Server → Tool/Resource → structured result.';if(n.id==='retriever')text='Question → embedding/search → top matching chunks → context injection → model.';if(n.id==='modelServer')text='App → HTTP API → model server → inference engine → CPU/GPU → generated response.';if(n.id==='runtime')text='Image + configuration → container runtime → isolated process + network + mounted storage.';if(n.id==='dns')text='Hostname → DNS query → resolver → IP address → client connects to destination.';if(n.id==='embedding')text='Text → tokenization → embedding model forward pass → dense vector → stored or compared by distance.';if(n.id==='vector')text='Vector in → approximate nearest-neighbor index (HNSW etc.) → top-K closest vectors + payloads out.';if(n.id==='agentLoop')text='Goal → model reasons → picks a tool → tool executes → result observed → loop until done → final answer.';if(n.id==='cicd')text='Push/PR event → runner picks up job → test → build → artifact published → deploy step promotes it.';if(n.id==='tls')text='Client hello → certificate verification → key exchange → symmetric encryption for the whole session.';if(n.id==='proxy')text='Request hits one public port → hostname/path inspected → routed to the matching internal service → response relayed.';if(n.id==='queue')text='Producer publishes → broker stores + orders → consumer pulls when ready → acknowledgement removes the message.';if(n.id==='backup')text='Snapshot → deduplicate + encrypt → ship to remote storage → verify → restore is a rehearsed path, not a hope.';return `<div class="section"><h3>🔬 Mechanism</h3><div class="eli5"><p>${text}</p></div></div>`}
  function engineeringHtml(n){return `<div class="section"><h3>🧰 Engineering depth</h3><div class="chips"><span class="chip">process</span><span class="chip">port/protocol</span><span class="chip">API contract</span><span class="chip">config/env</span><span class="chip">runtime</span><span class="chip">source subsystem</span></div><p class="source" style="margin-top:8px">Z5 is intentionally implementation-oriented. Exact values belong to implementation entries, not the permanent concept node.</p></div>`}
  function renderWelcome(){
    $('#insEyebrow').textContent='START HERE';$('#insIcon').textContent='🗺️';$('#insTitle').textContent='The Whole Lab';$('#insPath').textContent='World view · stable geography';
    $('#insBody').innerHTML=`<div class="eli5"><b>TOP-DOWN</b><p>Start with the physical world. Click a district, zoom to concepts, then reveal real tools only when you need them.</p></div><div class="six"><div class="fact"><b>WORLD</b><span>Complete reference universe</span></div><div class="fact"><b>LENS</b><span>${lensDefs[state.lens].label}</span></div><div class="fact"><b>ZOOM</b><span>${$('#zoomLabel').textContent}</span></div><div class="fact"><b>RULE</b><span>Position never changes</span></div></div><div class="section"><h3>Start a guided mission</h3><div class="chips"><button class="chip" data-go-mission="chatbot">▶ Local Chatbot</button><button class="chip" data-go-mission="rag">▶ Local RAG</button><button class="chip" data-go-mission="mcp">▶ MCP Agent</button></div></div><div class="section"><h3>Try this</h3><div class="chips"><button class="chip" data-go-search="MCP">Search MCP</button><button class="chip" data-go-builder="1">Open Builder</button></div></div>`;renderActions(null)
  }
  function renderActions(n){
    const defs=[['focus','👁','FOCUS'],['trace','⚡','TRACE'],['show','▶','SHOW ME'],['xray','🔬','X-RAY'],['compare','⚔','COMPARE'],['build','🧩','BUILD WITH'],['learn','📚','LEARN']];
    $('#actionRail').innerHTML=defs.map(([id,ic,lab])=>{const disabled=(!n&&['focus','trace','show','xray','compare','learn'].includes(id))||(id==='compare'&&n&&!(n.implementations?.length));return `<button data-action="${id}" ${disabled?'disabled':''} class="${state[id]?'active':''}">${ic}<br>${lab}</button>`}).join('');
    $$('#actionRail button').forEach(b=>b.addEventListener('click',()=>handleAction(b.dataset.action,n)))
  }
  function handleAction(action,n){
    if(action==='focus'){state.focus=!state.focus;renderMap();renderInspector()}
    if(action==='trace'){state.trace=!state.trace;renderMap();renderInspector()}
    if(action==='show')showMechanism(n)
    if(action==='xray'){if(!state.xray){state.xrayReturnDepth=state.depth;state.xray=true;state.depth=Math.max(state.depth,4)}else{state.xray=false;if(state.xrayReturnDepth!==null)state.depth=state.xrayReturnDepth;state.xrayReturnDepth=null}renderMap();renderInspector()}
    if(action==='compare')openCompare(n.id)
    if(action==='build')openBuilder(n?.id)
    if(action==='learn')openLearn(n)
  }
  function setMissionButton(playing){const b=$('#missionPlay');b.textContent=playing?'Ⅱ':'▶';b.setAttribute('aria-label',playing?'Pause mission':'Play mission')}
  function stopMission(clearPath=true){if(state.missionTimer){clearInterval(state.missionTimer);state.missionTimer=null}setMissionButton(false);if(clearPath){state.highlightPath=[];const t=$('#toast');clearTimeout(t._to);t.classList.remove('show')}state.missionStep=-1}
  function bestLensFor(n){const t=n?.tags||[];if(t.includes('ai'))return 'ai';if(t.includes('network'))return 'network';if(t.includes('data'))return 'data';if(t.includes('security'))return 'security';if(t.includes('performance'))return 'performance';return 'physical'}
  function showMechanism(n){stopMission(false);const maps={mcp:['user','agentLoop','mcp','tool','publicApi'],retriever:['corpus','chunker','embedding','vector','retriever','modelServer','model'],modelServer:['chat','modelServer','inference','gpu','model'],runtime:['ide','runtime','modelServer','observe'],dns:['user','dns','router','proxy'],proxy:['remote','router','proxy','tls','modelServer'],agentLoop:['user','agentLoop','model','tool','memory']};state.highlightPath=maps[n.id]||[n.id,...edges.filter(e=>e.a===n.id).slice(0,3).map(e=>e.b)];state.lens='mission';renderMap();toast(`▶ SHOW ME: ${n.name} · follow the bright path`)}
  function openCompare(id){const n=byId[id];const impls=n?.implementations;if(!impls?.length){toast('Comparison is available when a concept has multiple reference implementations.');return}$('#modalTitle').textContent=`⚔ Compare · ${n.name}`;const accent=COLORS[n.district]||'#29405a';$('#modalBody').innerHTML=`<div class="compare-grid" style="--accent:${accent}">${impls.map(i=>`<div class="compare-card"><h3>${i.name}</h3><div class="kv"><b>ROLE</b><span>${i.role}</span></div><div class="kv"><b>COMPLEXITY</b><span>${i.complexity}</span></div><div class="kv"><b>SCALE</b><span>${i.scale}</span></div><div class="kv"><b>HARDWARE</b><span>${i.hardware}</span></div><div class="kv"><b>BEST FOR</b><span>${i.ideal}</span></div><div class="kv"><b>TRADEOFF</b><span>${i.tradeoff}</span></div><div class="source"><a href="${i.source}" target="_blank" rel="noreferrer">Official source ↗</a></div></div>`).join('')}</div>`;openModal()}
  const builderParts=[['model','🧠 Model'],['tool','🛠 Tool'],['loop','🔁 Loop'],['memory','💾 Memory'],['mcp','🔌 MCP'],['retriever','🔎 Retriever'],['vector','🔢 Vector Store'],['workflow','🏭 Workflow']];let builderSet=new Set(['model']);
  function openBuilder(seed){if(seed&&['model','tool','agentLoop','memory','mcp','retriever','vector','workflow'].includes(seed))builderSet.add(seed==='agentLoop'?'loop':seed);$('#modalTitle').textContent='🧩 System Builder';renderBuilder();openModal()}
  function renderBuilder(){const partAccent=id=>COLORS[byId[id==='loop'?'agentLoop':id]?.district]||'#29405a';const parts=builderParts.map(([id,label])=>`<button class="partbtn ${builderSet.has(id)?'on':''}" data-part="${id}" style="--accent:${partAccent(id)}"><span>${label}</span><b>${builderSet.has(id)?'ON':'+'}</b></button>`).join('');const flow=[...builderSet].map(id=>`<span class="bnode" style="--accent:${partAccent(id)}">${builderParts.find(x=>x[0]===id)?.[1]||id}</span>`).join('<span class="barrow">→</span>');let cap='Prompted model';if(builderSet.has('model')&&builderSet.has('tool'))cap='Tool-using AI';if(builderSet.has('model')&&builderSet.has('tool')&&builderSet.has('loop'))cap='Agent';if(cap==='Agent'&&builderSet.has('memory'))cap='Stateful Agent';if(builderSet.has('model')&&builderSet.has('retriever')&&builderSet.has('vector'))cap='RAG-capable AI';if(builderSet.has('model')&&builderSet.has('tool')&&builderSet.has('loop')&&builderSet.has('mcp'))cap='MCP-enabled Agent';if(builderSet.has('workflow')&&builderSet.has('loop'))cap='Automated Agent Workflow';$('#modalBody').innerHTML=`<div class="builder-grid"><div class="builder-parts">${parts}</div><div class="builder-canvas"><div class="eyebrow">YOUR MACHINE</div><h2 style="margin:8px 0 14px">${cap}</h2><div class="builder-flow">${flow||'<span class="source">Choose components.</span>'}</div><div class="capability"><b>CAPABILITY UNLOCKED</b><p style="margin:5px 0 0;color:var(--muted);font-size:13px">${cap}. Add or remove components and watch the system identity change.</p></div></div></div>`;$$('.partbtn').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.part;builderSet.has(id)?builderSet.delete(id):builderSet.add(id);renderBuilder()}))}
  function openLearn(n){const step=id=>byId[id]?`<button data-go-node="${id}">${byId[id].name}</button>`:`<span>${id}</span>`;const pre=(n.prereq||[]),next=(n.next||[]);$('#modalTitle').textContent=`📚 Learning Path · ${n.name}`;$('#modalBody').innerHTML=`<div class="eyebrow">PREREQUISITES → CURRENT → UNLOCKS</div><div class="learn-chain" style="margin-top:14px">${pre.map(step).join('<b>→</b>')}${pre.length?'<b>→</b>':''}<span class="current">${n.name}</span>${next.length?'<b>→</b>':''}${next.map(step).join('<b>→</b>')}</div><div class="eli5" style="margin-top:18px"><b>PATTERN</b><p>Learn the dependency immediately before the concept, then build one tiny working path that uses it. Every step above is clickable — travel the chain.</p></div>`;openModal()}
  function openModal(){$('#overlay').classList.add('open')}function closeModal(){$('#overlay').classList.remove('open')}
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._to);t._to=setTimeout(()=>t.classList.remove('show'),2400)}
  function search(){const q=$('#searchInput').value.trim().toLowerCase();if(!q)return;stopMission(true);let scored=nodes.map(n=>{const hay=[n.name,n.role,n.eli5,...(n.aliases||[]),...(n.implementations||[]).map(i=>i.name)].join(' ').toLowerCase();let s=0;if(hay===q)s=100;if(n.name.toLowerCase()===q)s=95;if((n.aliases||[]).some(a=>a===q))s=90;if(hay.includes(q))s=Math.max(s,60);q.split(/\s+/).forEach(w=>{if(w.length>2&&hay.includes(w))s+=5});return{n,s}}).sort((a,b)=>b.s-a.s);const hit=scored[0];if(!hit||hit.s<5){toast(`No strong match for “${q}”. Try a concept, product, or goal.`);return}state.depth=Math.max(state.depth,2);select(hit.n.id);state.lens=bestLensFor(hit.n);renderMap();renderInspector();toast(`You searched “${q}” → ${hit.n.name}`)}
  function playMission(){const id=$('#missionSelect').value,m=missions.find(x=>x.id===id);if(state.missionTimer){stopMission(false);toast('Mission paused.');return}state.mission=m;state.lens='mission';state.highlightPath=[];state.missionStep=-1;setMissionButton(true);const tick=()=>{state.missionStep++;if(state.missionStep>=m.path.length){clearInterval(state.missionTimer);state.missionTimer=null;setMissionButton(false);toast(`Mission complete: ${m.name}`);return}state.highlightPath=m.path.slice(0,state.missionStep+1);renderMap();const n=byId[m.path[state.missionStep]];toast(`${state.missionStep+1}/${m.path.length} · ${n?.name||m.path[state.missionStep]}`)};tick();state.missionTimer=setInterval(tick,1100)}
  function setDepth(d){state.depth=Math.max(0,Math.min(5,d));state.scale=[.88,.96,1.02,1.08,1.13,1.18][state.depth];renderMap();renderInspector()}
  function home(){stopMission(true);state.selected=null;state.selectedEdge=null;state.history=[];state.focus=false;state.trace=false;state.xray=false;state.xrayReturnDepth=null;state.highlightPath=[];state.lens='physical';state.panX=0;state.panY=0;state.scale=.96;state.depth=1;renderMap();renderWelcome();inspector.classList.remove('open')}
  let dragging=false,last={x:0,y:0};svg.addEventListener('pointerdown',e=>{if(e.target.closest?.('.node,.district,.impl'))return;dragging=true;last={x:e.clientX,y:e.clientY};svg.setPointerCapture(e.pointerId)});svg.addEventListener('pointermove',e=>{if(!dragging)return;state.panX+=e.clientX-last.x;state.panY+=e.clientY-last.y;last={x:e.clientX,y:e.clientY};updateTransform()});svg.addEventListener('pointerup',()=>dragging=false);svg.addEventListener('pointercancel',()=>dragging=false);
  function goBack(){stopMission(true);state.xrayReturnDepth=null;const h=state.history.pop();if(!h){home();return}state.selected=h.selected;state.selectedEdge=h.selectedEdge;state.depth=h.depth;state.lens=h.lens;if(h.panX!==undefined){state.panX=h.panX;state.panY=h.panY}state.scale=[.88,.96,1.02,1.08,1.13,1.18][state.depth];state.focus=false;state.trace=false;state.xray=false;state.highlightPath=[];renderMap();renderInspector()}
  $('#zoomIn').addEventListener('click',()=>setDepth(state.depth+1));$('#zoomOut').addEventListener('click',()=>setDepth(state.depth-1));$('#backBtn').addEventListener('click',goBack);$('#homeBtn').addEventListener('click',home);$('#searchBtn').addEventListener('click',search);$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')search()});
  function startMission(id){stopMission(true);$('#missionSelect').value=id;inspector.classList.remove('open');playMission()}
  $('#crumbs').addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.crumbHome)home();else if(t.dataset.crumbDistrict)select(t.dataset.crumbDistrict)});
  $('#insBody').addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.goMission)startMission(t.dataset.goMission);else if(t.dataset.goSearch){$('#searchInput').value=t.dataset.goSearch;search()}else if(t.dataset.goBuilder)openBuilder();else if(t.dataset.goDepth)setDepth(+t.dataset.goDepth)});
  $('#modalBody').addEventListener('click',e=>{const t=e.target.closest('button[data-go-node]');if(!t)return;closeModal();select(t.dataset.goNode)});
  $$('.lens[data-lens]').forEach(b=>b.addEventListener('click',()=>{stopMission(true);state.lens=b.dataset.lens;state.highlightPath=[];renderMap();renderInspector()}));
  $('#moreLens').addEventListener('click',()=>{$('#modalTitle').textContent='More lenses';$('#modalBody').innerHTML=`<div class="chips">${['software','performance','cost','learning'].map(id=>`<button class="lens" data-more="${id}">${lensDefs[id].label}</button>`).join('')}</div>`;openModal();$$('[data-more]').forEach(b=>b.addEventListener('click',()=>{stopMission(true);state.lens=b.dataset.more;closeModal();renderMap();renderInspector()}))});
  $('#modalClose').addEventListener('click',closeModal);$('#overlay').addEventListener('click',e=>{if(e.target===$('#overlay'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#overlay').classList.contains('open'))closeModal();else if(!$('#tutorial').classList.contains('hidden'))$('#tutorial').classList.add('hidden')}});
  $('#missionPlay').addEventListener('click',playMission);missions.forEach(m=>{const o=document.createElement('option');o.value=m.id;o.textContent=m.name;$('#missionSelect').appendChild(o)});setMissionButton(false);
  let ti=0;const tsteps=$$('.tstep');
  function renderTutorial(){tsteps.forEach((s,i)=>s.classList.toggle('active',i===ti));$('#tCount').textContent=`${ti+1} / ${tsteps.length}`;$('#tNext').textContent=ti===tsteps.length-1?'Enter Atlas →':'Next →'}
  function closeTutorial(){ $('#tutorial').classList.add('hidden'); }
  function nextTutorial(){ if(ti===tsteps.length-1){closeTutorial();return} ti++;renderTutorial(); }
  function tapSafe(el,fn){let lastTouch=0;el.addEventListener('touchend',e=>{lastTouch=Date.now();e.preventDefault();fn(e)},{passive:false});el.addEventListener('click',e=>{if(Date.now()-lastTouch<650)return;fn(e)});}
  tapSafe($('#tNext'),nextTutorial);tapSafe($('#tSkip'),closeTutorial);tapSafe($('#helpBtn'),()=>{ti=0;renderTutorial();$('#tutorial').classList.remove('hidden')});
  $('.ins-head').addEventListener('click',()=>{if(innerWidth<900)inspector.classList.toggle('open')});
  renderMini();renderMap();renderWelcome();window.__atlasReady=true;
})();
