(() => {
  document.documentElement.classList.add('js-running');
  const NS='http://www.w3.org/2000/svg';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const COLORS={iface:'#42e8e0',cloudx:'#a5b7cc',forge:'#9b6cff',serving:'#ff9f43',agent:'#dffe02',knowledge:'#40e68b',proving:'#d4537e',foundation:'#69839d',shipyard:'#ff5d73'};
  const lensDefs={
    physical:{label:'PHYSICAL',cats:['foundation','iface','cloudx'],tags:['physical']},
    ai:{label:'AI',cats:['forge','serving','agent','knowledge','proving'],tags:['ai']},
    network:{label:'NETWORK',cats:['cloudx','shipyard'],tags:['network']},
    data:{label:'DATA',cats:['knowledge','agent'],tags:['data']},
    security:{label:'SECURITY',cats:['shipyard','cloudx'],tags:['security']},
    mission:{label:'MISSION',cats:[],tags:[]}, software:{label:'SOFTWARE',cats:['iface','shipyard','agent','foundation'],tags:['software']},
    performance:{label:'PERFORMANCE',cats:['serving','foundation','forge'],tags:['performance']}, cost:{label:'COST',cats:['serving','cloudx','forge'],tags:['cost']}, learning:{label:'LEARNING',cats:[],tags:['learning']}
  };
  const districts=[
    {id:'iface',name:'Interface Deck',icon:'🎛️',sub:'Where humans meet AI · chat · IDE · surfaces agents act through',x:36,y:30,w:500,h:160,tags:['physical','software','ai']},
    {id:'cloudx',name:'Cloud Exchange',icon:'☁️',sub:'Rented intelligence · APIs · GPU cloud',x:1190,y:30,w:375,h:110,tags:['network','cost','security']},
    {id:'forge',name:'Model Forge',icon:'🔥',sub:'What models are · training · weights · quantization',x:36,y:250,w:480,h:160,tags:['ai','performance','cost']},
    {id:'serving',name:'Inference Works',icon:'⚡',sub:'Where models run · serving · GPU · multimodal',x:560,y:250,w:480,h:160,tags:['ai','performance','cost','physical']},
    {id:'agent',name:'Agent Operations',icon:'🤖',sub:'AI that acts · loops · tools · MCP · prompting',x:1080,y:240,w:485,h:210,tags:['ai','software','data']},
    {id:'knowledge',name:'Knowledge Works',icon:'📚',sub:'What AI knows · corpus · embeddings · retrieval',x:36,y:480,w:700,h:160,tags:['data','ai']},
    {id:'proving',name:'Proving Grounds',icon:'📏',sub:'Reserved territory · safety · red-teaming · benchmarks grow here',x:780,y:500,w:785,h:110,tags:['ai','learning']},
    {id:'foundation',name:'Foundation',icon:'🏗️',sub:'What AI runs on · hosts · CPU · memory · containers',x:36,y:700,w:700,h:160,tags:['physical','performance','software']},
    {id:'shipyard',name:'Shipyard',icon:'🚢',sub:'Ship and watch AI apps · git · CI/CD · secrets · gateway',x:780,y:690,w:785,h:160,tags:['software','security','network']}
  ];
  const nodeSeeds={
    iface:[['user','User','👤','human intent'],['chat','Chat Interface','💬','conversation UI'],['ide','IDE / Coding Agent','🧑‍💻','build with AI'],['shell','Terminal / Shell','⌨️','where agents run commands'],['browser','Browser','🌐','where agents browse']],
    cloudx:[['cloudAi','Cloud AI API','☁️','remote models'],['publicApi','Public API / Data','🌍','external capabilities'],['gpuCloud','GPU Cloud','🧊','rented accelerators']],
    forge:[['model','Model','🧠','learned behavior'],['weights','Model Weights','🏋️','learned parameters'],['tokenizer','Tokenizer + Context','🪙','text ↔ tokens'],['finetune','Fine-tuning / LoRA','🔧','adapt a model'],['quant','Quantization','🗜️','shrink models']],
    serving:[['inference','Inference Engine','⚡','executes model'],['modelServer','Model Server / API','📡','serves inference'],['gpu','GPU / Accelerator','🎮','AI’s parallel math'],['multimodal','Multimodal AI','👁️','beyond text'],['cache','Cache / KV State','⚡','fast serving memory']],
    agent:[['agentLoop','Agent Loop','🤖','observe → decide → act'],['tool','Tool','🛠️','external action'],['mcp','MCP Interface','🔌','standard capability bridge'],['memory','Agent Memory','🧠','persistent context'],['prompting','Prompt Engineering','📝','shape model context'],['workflow','Workflow Engine','🏭','repeatable automation'],['queue','Queue / Event','📨','asynchronous work'],['evals','Evals / Benchmarks','📏','measure quality']],
    knowledge:[['corpus','Corpus / Files','📚','source knowledge'],['chunker','Parser + Chunker','✂️','prepare documents'],['embedding','Embedding Model','🔢','meaning → vectors'],['vector','Vector Store','🔢','similarity memory'],['retriever','Retriever / Search','🔎','find relevant context'],['appdb','Application Database','🗃️','structured state for AI apps']],
    proving:[],
    foundation:[['host','Host Machine','🖥️','physical computer'],['cpu','CPU','🧮','general compute'],['ram','RAM','🧠','working memory'],['storage','Persistent Storage','💽','keeps data'],['runtime','Container Runtime','🐳','isolated services']],
    shipyard:[['git','Git / Repo','🌿','version control'],['github','Remote Forge','🐙','shared repository'],['cicd','CI / CD','⚙️','test / build / deploy'],['secrets','Identity + Secrets','🔑','credentials / API keys'],['observe','Observability','📡','logs · metrics · traces'],['gateway','Gateway / HTTPS','🚦','one safe front door']]
  };
  const roles={
    user:{eli5:'You provide the goal. Every AI system ultimately exists to turn human intent into useful work.',why:'Starts the system',in:'Goal / question',out:'Intent',unlocks:'Every mission',tags:['physical','learning']},
    model:{eli5:'The learned brain. It predicts useful outputs from the context it receives.',why:'Generate or classify',in:'Tokens / context',out:'Probabilities / tokens',unlocks:'Chat, coding, agents',tags:['ai','performance','cost'],prereq:['tokenizer'],next:['inference','modelServer','agentLoop']},
    inference:{eli5:'The engine that actually runs model math on CPU/GPU hardware.',why:'Execute the model',in:'Weights + tokens',out:'Model computation',unlocks:'Local AI',tags:['ai','performance'],prereq:['model','weights','cpu','gpu'],next:['modelServer']},
    modelServer:{eli5:'Turns inference into a service other apps can call.',why:'Expose models to apps',in:'API request',out:'Model response',unlocks:'Chat apps, RAG, agents',tags:['ai','network','software'],aliases:['ollama','run llm locally','local inference','llm api','serve model'],prereq:['inference','model'],next:['chat','agentLoop','retriever'],implementations:[
      {name:'Ollama',role:'Simple local model serving',complexity:'Low',scale:'Personal / small server',hardware:'CPU/GPU local',ideal:'Fast local setup',tradeoff:'Less serving control than dedicated high-throughput stacks',source:'https://docs.ollama.com/api/introduction'},
      {name:'llama.cpp',role:'Low-level local inference + server',complexity:'Medium',scale:'Device → workstation',hardware:'Broad CPU/GPU support',ideal:'Maximum local/runtime control',tradeoff:'More hands-on configuration',source:'https://github.com/ggml-org/llama.cpp'},
      {name:'vLLM',role:'High-throughput model serving',complexity:'Higher',scale:'Server / multi-GPU',hardware:'GPU-oriented',ideal:'Serving many requests',tradeoff:'Heavier operational footprint',source:'https://docs.vllm.ai/en/latest/'}]},
    embedding:{eli5:'Turns meaning into coordinates so similar things end up near each other mathematically.',why:'Semantic search',in:'Text / data',out:'Vector',unlocks:'RAG and similarity search',tags:['ai','data'],prereq:['model'],next:['vector','retriever'],implementations:[{name:'sentence-transformers',role:'Local embedding models',complexity:'Low–Medium',scale:'Laptop → server',hardware:'CPU or GPU',ideal:'Self-hosted semantic search',tradeoff:'Model choice matters; quality varies by domain',source:'https://sbert.net/'}]},
    vector:{eli5:'A searchable warehouse for embeddings. Ask for “things most like this” and it finds nearby vectors mathematically.',why:'Similarity retrieval',in:'Vectors',out:'Nearest matches',unlocks:'RAG, semantic memory',tags:['data','ai'],aliases:['vector db','vector database','vector store','qdrant'],prereq:['embedding'],next:['retriever'],implementations:[{name:'Qdrant',role:'Vector search database',complexity:'Medium',scale:'Local → server',hardware:'CPU/RAM/storage',ideal:'Dedicated vector retrieval',tradeoff:'Adds another service',source:'https://qdrant.tech/documentation/overview/vector-search/'},{name:'Chroma',role:'Embedded vector store',complexity:'Low',scale:'Prototype → small app',hardware:'In-process',ideal:'Getting RAG working fast',tradeoff:'Less suited to heavy multi-service load',source:'https://docs.trychroma.com/'},{name:'pgvector',role:'Vectors inside PostgreSQL',complexity:'Medium',scale:'With your existing DB',hardware:'Your Postgres host',ideal:'One database for rows and vectors',tradeoff:'Tuning lives inside Postgres ops',source:'https://github.com/pgvector/pgvector'}]},
    retriever:{eli5:'The librarian. It searches your knowledge and hands the model only the useful pieces.',why:'Find useful context',in:'Question / vector',out:'Relevant chunks',unlocks:'RAG',tags:['data','ai'],aliases:['rag search','retrieval'],prereq:['corpus','chunker','embedding','vector'],next:['model'],implementations:[{name:'LlamaIndex',role:'RAG framework',complexity:'Medium',scale:'Prototype → production',hardware:'App-level',ideal:'Document ingestion + retrieval pipelines',tradeoff:'Framework abstractions to learn',source:'https://docs.llamaindex.ai/'},{name:'LangChain',role:'LLM app framework with retrievers',complexity:'Medium',scale:'Prototype → production',hardware:'App-level',ideal:'Composable chains around retrieval',tradeoff:'Fast-moving API surface',source:'https://python.langchain.com/docs/concepts/retrievers/'}]},
    mcp:{eli5:'A standard connection layer that lets AI applications discover and use external tools and resources.',why:'Connect AI to capabilities',in:'Tool/resource request',out:'Structured result',unlocks:'Portable AI integrations',tags:['ai','network','software','security'],aliases:['model context protocol','ai tools','connect ai to github','mcp server'],prereq:['tool'],next:['agentLoop'],implementations:[{name:'MCP',role:'Host/client/server protocol',complexity:'Medium',scale:'Local or remote',hardware:'Any host',ideal:'Standard AI-tool integrations',tradeoff:'Security and permission design matter',source:'https://modelcontextprotocol.io/docs/2026-07-28/learn/architecture'}]},
    agentLoop:{eli5:'A model that repeatedly looks at the situation, chooses an action, uses a tool, observes the result, and continues.',why:'Multi-step work',in:'Goal + observations',out:'Actions + final result',unlocks:'Autonomous workflows',tags:['ai','software','data'],aliases:['agent','ai agent','autonomous agent'],prereq:['model','tool'],next:['memory','mcp','workflow'],implementations:[{name:'Claude Agent SDK',role:'Agent loop framework',complexity:'Medium',scale:'Script → production agents',hardware:'App-level + API',ideal:'Tool-using agents with strong model reasoning',tradeoff:'Anchored to one model provider',source:'https://docs.claude.com/en/api/agent-sdk/overview'},{name:'LangGraph',role:'Graph-based agent orchestration',complexity:'Medium–High',scale:'Prototype → production',hardware:'App-level',ideal:'Explicit control over agent state machines',tradeoff:'More upfront structure to design',source:'https://langchain-ai.github.io/langgraph/'}]},
    tool:{eli5:'A capability the AI can invoke, such as reading a file, running code, browsing, or calling an API.',why:'Let AI act',in:'Structured arguments',out:'Tool result',unlocks:'Tool-using AI and agents',tags:['ai','software','security'],prereq:['model'],next:['mcp','agentLoop']},
    runtime:{eli5:'Runs applications in isolated containers so services can be packaged, moved, restarted and connected predictably.',why:'Package services',in:'Image + config',out:'Running container',unlocks:'Repeatable homelab services',tags:['physical','software','security'],aliases:['docker','containers','container runtime'],next:['modelServer','observe'],implementations:[{name:'Docker',role:'Container engine + tooling',complexity:'Low–Medium',scale:'Laptop → server',hardware:'Host OS',ideal:'Self-hosted services',tradeoff:'Adds container/network/storage concepts',source:'https://docs.docker.com/engine/'}]},
    gateway:{eli5:'One safe front door. A reverse proxy routes requests to the right internal service, and HTTPS seals the traffic so networks in between can route it but not read it.',why:'Expose AI services safely',in:'HTTP request',out:'Routed, encrypted traffic',unlocks:'Serving AI beyond localhost',tags:['network','security'],aliases:['reverse proxy','caddy','https','tls','proxy'],next:['modelServer'],implementations:[{name:'Caddy',role:'Reverse proxy with automatic HTTPS',complexity:'Low',scale:'Home → production',hardware:'Small service',ideal:'Simple secure publishing',tradeoff:'Still requires exposure/access decisions',source:'https://caddyserver.com/docs/quick-starts/reverse-proxy'},{name:"Let's Encrypt",role:'Free automated certificates',complexity:'Low',scale:'Any public site',hardware:'None (CA service)',ideal:'Auto-renewed HTTPS everywhere',tradeoff:'Requires a domain + renewal automation',source:'https://letsencrypt.org/docs/'}]},
    observe:{eli5:'Your system’s senses. Metrics show how much, logs show what happened, traces show where requests traveled.',why:'Understand system behavior',in:'Telemetry',out:'Metrics / logs / traces',unlocks:'Troubleshooting and performance work',tags:['security','performance','software'],aliases:['observability','monitoring','otel','opentelemetry'],implementations:[{name:'OpenTelemetry',role:'Telemetry instrumentation standard',complexity:'Medium',scale:'Single service → distributed systems',hardware:'App/collector resources',ideal:'Vendor-neutral telemetry',tradeoff:'Collection is not the same as storage/visualization',source:'https://opentelemetry.io/docs/concepts/signals/'},{name:'Prometheus',role:'Metrics collection + alerting',complexity:'Medium',scale:'Homelab → production',hardware:'Modest server',ideal:'Pull-based metrics with a query language',tradeoff:'Metrics only; logs/traces need companions',source:'https://prometheus.io/docs/'},{name:'Grafana',role:'Dashboards + visualization',complexity:'Low–Medium',scale:'Homelab → production',hardware:'Small service',ideal:'One pane of glass over many sources',tradeoff:'Dashboards need gardening to stay honest',source:'https://grafana.com/docs/'}]},
    github:{eli5:'A remote home for Git repositories where code collaboration, review and automation can happen.',why:'Share and coordinate code',in:'Commits / pull requests',out:'Repository state',unlocks:'Collaboration + CI/CD',tags:['software','network','security'],aliases:['github','remote repo'],next:['cicd'],implementations:[{name:'GitHub',role:'Hosted collaboration platform',complexity:'Low',scale:'Solo → enterprise',hardware:'None (SaaS)',ideal:'Default home for open + private code',tradeoff:'Your workflow lives on someone else\'s platform',source:'https://docs.github.com/'},{name:'Forgejo',role:'Self-hosted Git forge',complexity:'Medium',scale:'Personal → team',hardware:'Small service',ideal:'Owning your forge in the homelab',tradeoff:'You operate what GitHub operates for you',source:'https://forgejo.org/docs/'}]},
    cicd:{eli5:'An automated assembly line that tests, builds and deploys code when repository events happen.',why:'Automate delivery',in:'Code change',out:'Tests / build / deployment',unlocks:'Repeatable shipping',tags:['software','security'],aliases:['github actions','ci cd','pipeline'],prereq:['git','github'],next:['observe'],implementations:[{name:'GitHub Actions',role:'Hosted CI/CD',complexity:'Low–Medium',scale:'Solo → enterprise',hardware:'Hosted or self-hosted runners',ideal:'CI living next to the repo',tradeoff:'YAML sprawl; runner minutes cost at scale',source:'https://docs.github.com/actions'},{name:'GitLab CI',role:'Integrated CI/CD',complexity:'Medium',scale:'Solo → enterprise',hardware:'Hosted or self-managed',ideal:'Single-platform repo + pipeline + registry',tradeoff:'Heavier platform to self-host',source:'https://docs.gitlab.com/ee/ci/'}]},
    gpu:{eli5:'A massively parallel calculator. AI workloads use it to perform many matrix operations at once.',why:'Accelerate AI math',in:'Model operations',out:'Fast parallel compute',unlocks:'Faster/larger local models',tags:['physical','performance','cost'],aliases:['vram','graphics card','accelerator'],next:['inference'],implementations:[{name:'CUDA',role:'NVIDIA GPU compute stack',complexity:'Medium',scale:'Laptop → datacenter',hardware:'NVIDIA GPUs',ideal:'Broadest AI framework support',tradeoff:'Vendor lock-in',source:'https://docs.nvidia.com/cuda/'},{name:'ROCm',role:'AMD GPU compute stack',complexity:'Medium–High',scale:'Workstation → server',hardware:'AMD GPUs',ideal:'Open-source stack on AMD hardware',tradeoff:'Narrower official support matrix',source:'https://rocm.docs.amd.com/'}]},
    ram:{eli5:'Fast temporary working space used by the operating system, services, model weights and caches.',why:'Hold active data',in:'Active program data',out:'Fast memory access',unlocks:'Larger workloads',tags:['physical','performance','cost']},
    chat:{eli5:'The conversation surface. It turns a model API into something a person can actually talk to.',why:'Human-friendly AI access',in:'User messages',out:'Model responses',unlocks:'Daily-driver local AI',tags:['software','ai'],implementations:[{name:'Open WebUI',role:'Self-hosted chat interface',complexity:'Low',scale:'Personal → team',hardware:'Small service',ideal:'Chat UI over local model servers',tradeoff:'Another service to run and update',source:'https://docs.openwebui.com/'}]},
    appdb:{eli5:'Structured, durable memory for applications. Rows, relations, and transactions instead of loose files.',why:'Reliable structured state',in:'Queries / writes',out:'Consistent data',unlocks:'Stateful applications',tags:['data','software'],implementations:[{name:'PostgreSQL',role:'Relational database',complexity:'Medium',scale:'Single node → clustered',hardware:'CPU/RAM/storage',ideal:'General-purpose application data',tradeoff:'Operational care: backups, tuning, upgrades',source:'https://www.postgresql.org/docs/'},{name:'SQLite',role:'Embedded file database',complexity:'Low',scale:'Single process',hardware:'Any',ideal:'Local apps and small services',tradeoff:'Single-writer; not built for many concurrent services',source:'https://sqlite.org/docs.html'}]},
    cache:{eli5:'Very fast short-term memory. Keeps hot data close so systems stop recomputing or refetching it.',why:'Speed + temporary state',in:'Keys / values',out:'Microsecond reads',unlocks:'Fast apps, sessions, queues',tags:['data','performance'],implementations:[{name:'Redis',role:'In-memory data store',complexity:'Low–Medium',scale:'Single node → clustered',hardware:'RAM-heavy',ideal:'Cache, sessions, queues, pub/sub',tradeoff:'Working set sized to RAM',source:'https://redis.io/docs/latest/'},{name:'Valkey',role:'Open-governance Redis-compatible store',complexity:'Low–Medium',scale:'Single node → clustered',hardware:'RAM-heavy',ideal:'Drop-in open-source alternative',tradeoff:'Younger ecosystem',source:'https://valkey.io/docs/'}]},
    workflow:{eli5:'A factory line for repeatable automation: triggers, steps, retries, and connections between services.',why:'Repeatable automation',in:'Trigger / event',out:'Executed steps',unlocks:'Hands-off pipelines',tags:['software','ai'],aliases:['n8n','automation'],implementations:[{name:'n8n',role:'Visual workflow automation',complexity:'Low–Medium',scale:'Personal → team',hardware:'Small service',ideal:'Connecting APIs, AI steps, and homelab services',tradeoff:'Complex logic can outgrow visual flows',source:'https://docs.n8n.io/'},{name:'Apache Airflow',role:'Code-first orchestration',complexity:'Higher',scale:'Team → data platforms',hardware:'Server-class',ideal:'Scheduled data/ML pipelines as code',tradeoff:'Heavy for simple automations',source:'https://airflow.apache.org/docs/'}]},
    queue:{eli5:'A waiting line for work. Producers drop messages, consumers process them when ready — nothing is lost in between.',why:'Decouple + absorb bursts',in:'Messages / events',out:'Reliable delivery',unlocks:'Async, resilient systems',tags:['software','data'],implementations:[{name:'NATS',role:'Lightweight messaging system',complexity:'Low–Medium',scale:'Edge → distributed',hardware:'Tiny footprint',ideal:'Simple fast pub/sub and queues',tradeoff:'Fewer heavyweight broker features',source:'https://docs.nats.io/'},{name:'RabbitMQ',role:'Full-featured message broker',complexity:'Medium',scale:'Single node → clustered',hardware:'Modest server',ideal:'Routing, acknowledgements, work queues',tradeoff:'More concepts to operate correctly',source:'https://www.rabbitmq.com/docs'}]},
    secrets:{eli5:'The locked drawer for credentials. Services get the keys they need without keys living in code or configs.',why:'Protect credentials',in:'Auth requests',out:'Scoped secrets',unlocks:'Safe automation + deploys',tags:['security','software'],implementations:[{name:'Vaultwarden',role:'Self-hosted password manager server',complexity:'Low',scale:'Personal → small team',hardware:'Tiny service',ideal:'Human credentials in the homelab',tradeoff:'Unofficial server reimplementation; track upstream',source:'https://github.com/dani-garcia/vaultwarden/wiki'},{name:'HashiCorp Vault',role:'Machine secrets management',complexity:'Higher',scale:'Team → enterprise',hardware:'Dedicated service',ideal:'Dynamic secrets for services and CI',tradeoff:'Real operational overhead (sealing, policies)',source:'https://developer.hashicorp.com/vault/docs'}]},
    finetune:{eli5:'Teaching an existing model your specifics. Instead of training from scratch, you nudge a pretrained model with your own examples — LoRA does it by training tiny add-on layers.',why:'Specialize a model',in:'Base model + your examples',out:'Adapted weights / adapter',unlocks:'Domain-expert local models',tags:['ai','performance','cost'],aliases:['lora','fine tune','training','adapt model','train model'],prereq:['model','corpus','gpu'],next:['quant','weights','evals'],implementations:[{name:'Hugging Face PEFT',role:'Parameter-efficient fine-tuning (LoRA etc.)',complexity:'Medium',scale:'Single GPU → cluster',hardware:'GPU with enough VRAM',ideal:'Standard LoRA/QLoRA workflows',tradeoff:'Python ML stack to manage',source:'https://huggingface.co/docs/peft'},{name:'Unsloth',role:'Fast memory-efficient fine-tuning',complexity:'Medium',scale:'Consumer GPU friendly',hardware:'Single GPU',ideal:'Fine-tuning on homelab-class hardware',tradeoff:'Focused on supported model families',source:'https://docs.unsloth.ai/'}]},
    quant:{eli5:'Compressing a model by storing its numbers less precisely — like rounding prices to the nearest dollar. The model gets far smaller and faster, losing only a little quality.',why:'Fit models on real hardware',in:'Full-precision weights',out:'Smaller, faster weights',unlocks:'Big models on small machines',tags:['ai','performance','cost'],aliases:['gguf','quantize','4-bit','compression'],prereq:['weights'],next:['inference','modelServer'],implementations:[{name:'GGUF (llama.cpp)',role:'Quantized local model format',complexity:'Low–Medium',scale:'Phone → workstation',hardware:'CPU/GPU',ideal:'Running quantized models locally',tradeoff:'Quality drops as bits shrink — test your use case',source:'https://github.com/ggml-org/llama.cpp'},{name:'bitsandbytes',role:'On-the-fly 8/4-bit loading',complexity:'Medium',scale:'GPU workflows',hardware:'CUDA GPUs',ideal:'Quantized training + inference in Python',tradeoff:'Tied to the PyTorch/CUDA stack',source:'https://huggingface.co/docs/bitsandbytes'}]},
    multimodal:{eli5:'AI beyond text: models that see images, hear speech, or generate pictures and audio — the same predict-from-context idea applied to more senses.',why:'Perceive and generate media',in:'Images / audio / text',out:'Understanding or new media',unlocks:'Vision, voice, image generation',tags:['ai'],aliases:['vision','speech','image generation','whisper','stable diffusion','voice'],prereq:['model'],next:['inference','agentLoop'],implementations:[{name:'Whisper',role:'Speech-to-text model',complexity:'Low–Medium',scale:'Laptop → server',hardware:'CPU or GPU',ideal:'Local transcription pipelines',tradeoff:'Latency grows on CPU for long audio',source:'https://github.com/openai/whisper'},{name:'Stable Diffusion',role:'Image generation model family',complexity:'Medium',scale:'Single GPU',hardware:'GPU ~8GB+ VRAM',ideal:'Local image generation',tradeoff:'VRAM-hungry; prompt craft matters',source:'https://github.com/Stability-AI/stablediffusion'}]},
    prompting:{eli5:'Deliberately shaping everything the model reads — instructions, examples, retrieved context — because the input is the only steering wheel you have at runtime.',why:'Steer model behavior',in:'Task + raw context',out:'Structured model input',unlocks:'Reliable AI behavior without training',tags:['ai','software','learning'],aliases:['prompt engineering','context engineering','system prompt','few-shot'],prereq:['model','tokenizer'],next:['agentLoop','evals'],implementations:[{name:'Claude prompting guide',role:'Vendor prompt-engineering reference',complexity:'Low',scale:'Any prompt',hardware:'None',ideal:'Practical patterns: roles, examples, chain-of-thought',tradeoff:'Techniques shift as models improve',source:'https://docs.claude.com/en/docs/build-with-claude/prompt-engineering/overview'}]},
    evals:{eli5:'Measuring whether AI actually works: fixed test sets and scoring so you can compare models, prompts, and agents instead of trusting vibes.',why:'Know if changes help',in:'Model/agent + test cases',out:'Scores / regressions',unlocks:'Confident iteration',tags:['ai','software','performance'],aliases:['benchmark','evaluation','testing models','regression'],prereq:['model'],next:['finetune','prompting'],implementations:[{name:'lm-evaluation-harness',role:'Standard LLM benchmark runner',complexity:'Medium',scale:'Any local/API model',hardware:'Depends on model',ideal:'Comparing models on published benchmarks',tradeoff:'Benchmarks ≠ your task; add custom sets',source:'https://github.com/EleutherAI/lm-evaluation-harness'},{name:'promptfoo',role:'Prompt/agent eval + regression testing',complexity:'Low–Medium',scale:'Dev workflow',hardware:'None (drives APIs)',ideal:'CI-style tests for prompts and RAG',tradeoff:'You must write good test cases',source:'https://www.promptfoo.dev/docs/'}]},
    ide:{eli5:'Where you and an AI pair-write code together — the editor becomes a second brain that reads your files and proposes changes.',why:'Build software with AI',in:'Codebase + intent',out:'Code changes',unlocks:'AI-assisted development',tags:['software','ai'],aliases:['cursor','claude code','copilot','coding agent','ai ide'],next:['git','shell'],implementations:[{name:'Cursor',role:'AI-native code editor',complexity:'Low',scale:'Solo → team',hardware:'Any + API',ideal:'AI pair-programming inside a familiar editor',tradeoff:'Fork of VS Code to keep in sync',source:'https://docs.cursor.com/'},{name:'Claude Code',role:'Agentic coding CLI/IDE integration',complexity:'Low',scale:'Solo → team',hardware:'Any + API',ideal:'Terminal-native, tool-using coding agent',tradeoff:'Anchored to one model provider',source:'https://docs.claude.com/en/docs/claude-code/overview'}]},
    shell:{eli5:'The most direct way to control a machine — one line in, one result out. Agents use it the same way you do.',why:'Direct machine control',in:'Commands',out:'stdout / exit codes',unlocks:'Agents that can act, not just talk',tags:['physical','software'],aliases:['terminal','cli','bash','command line'],prereq:['ide'],next:['runtime']},
    browser:{eli5:'The web interface — for humans clicking links, and increasingly for agents that read pages and click buttons on your behalf.',why:'Reach the web',in:'URL / page state',out:'Rendered content / actions',unlocks:'Web-browsing agents',tags:['software','ai'],aliases:['web browsing agent','browser automation','headless browser'],next:['tool'],implementations:[{name:'Playwright',role:'Browser automation framework',complexity:'Medium',scale:'Script → production',hardware:'Any',ideal:'Reliable programmatic/agent browser control',tradeoff:'Another moving part to maintain',source:'https://playwright.dev/docs/intro'}]},
    cloudAi:{eli5:"Someone else's model, someone else's GPUs — you send a request, they send back an answer, no hardware required.",why:'Use frontier models without owning hardware',in:'API request + key',out:'Model response',unlocks:'Instant access to the best models',tags:['ai','cost'],aliases:['openai api','claude api','gemini api','chatgpt api'],next:['agentLoop'],implementations:[{name:'Anthropic API',role:'Hosted Claude models',complexity:'Low',scale:'Prototype → production',hardware:'None (hosted)',ideal:'Frontier reasoning without infra',tradeoff:'Cost scales with usage; vendor dependency',source:'https://docs.claude.com/en/api/overview'},{name:'OpenAI API',role:'Hosted GPT models',complexity:'Low',scale:'Prototype → production',hardware:'None (hosted)',ideal:'Broad model + tooling ecosystem',tradeoff:'Cost scales with usage; vendor dependency',source:'https://platform.openai.com/docs/overview'}]},
    publicApi:{eli5:"The outside world's programmable door — weather, maps, search, anything an agent might need to look up or act on.",why:'Give agents real-world capability',in:'HTTP request',out:'External data / effect',unlocks:'Agents that do real things',tags:['network','ai'],next:['mcp']},
    gpuCloud:{eli5:"Renting someone else's accelerator by the hour instead of buying your own — the fastest way to get GPU power you don't have at home.",why:"Access compute you don't own",in:'Job + payment',out:'Compute time',unlocks:'Training/serving without hardware',tags:['ai','cost'],aliases:['rented gpu','cloud gpu'],next:['inference','finetune'],implementations:[{name:'RunPod',role:'On-demand GPU rental',complexity:'Low',scale:'Hourly → dedicated',hardware:'Rented GPUs',ideal:'Spin up GPU compute fast, pay by the hour',tradeoff:'Spot capacity can be reclaimed',source:'https://docs.runpod.io/'},{name:'Lambda',role:'GPU cloud for AI workloads',complexity:'Low',scale:'Hourly → dedicated',hardware:'Rented GPUs',ideal:'AI-focused cloud instances',tradeoff:'Availability varies by GPU type/region',source:'https://docs.lambdalabs.com/'}]},
    weights:{eli5:'The actual learned numbers — millions or billions of parameters that encode everything the model ‘knows.’ Same architecture, different weights, different model.',why:'Store what was learned',in:'Training process',out:'A usable model',unlocks:'Inference, fine-tuning, sharing models',tags:['ai'],aliases:['checkpoint','model file','safetensors','gguf file'],prereq:['model'],next:['quant','inference']},
    tokenizer:{eli5:"Splits text into the chunks a model actually reads — and defines the window of how much it can 'see' at once.",why:'Text ↔ tokens bridge',in:'Raw text',out:'Token IDs',unlocks:'Everything downstream of a model',tags:['ai'],aliases:['context window','tokens','bpe'],next:['inference','prompting']},
    memory:{eli5:'What an agent remembers between steps — or between conversations, if it’s built to persist.',why:'Persistent context',in:'Past observations / results',out:'Recalled context',unlocks:"Agents that learn from their own history",tags:['ai','data'],aliases:['agent memory','conversation history','long-term memory'],prereq:['agentLoop'],next:['vector']},
    corpus:{eli5:'Your actual source material — documents, code, notes — before any AI touches it.',why:'Source knowledge for RAG or fine-tuning',in:'Raw files',out:'Text ready for processing',unlocks:'Retrieval or training grounded in your own data',tags:['data'],next:['chunker','finetune']},
    chunker:{eli5:'Breaks long documents into small enough pieces that a retriever can find precisely what’s relevant, not a whole book at once.',why:'Prepare documents for retrieval',in:'Raw documents',out:'Retrievable chunks',unlocks:'Precise RAG',tags:['data'],aliases:['text splitter','document chunking'],prereq:['corpus'],next:['embedding']},
    host:{eli5:'The physical or virtual computer everything else actually runs on.',why:'Physical substrate',in:'Power + network',out:'Compute capacity',unlocks:'Everything above it',tags:['physical'],next:['cpu','gpu','ram']},
    cpu:{eli5:"The general-purpose brain of the machine — flexible, but not built for the massive parallel math AI needs.",why:'General compute',in:'Instructions',out:'Sequential execution',unlocks:"Everything that isn't matrix math",tags:['physical','performance'],prereq:['host'],next:['inference']},
    storage:{eli5:'Where data survives a restart — model weights, databases, and files all live here.',why:'Keep data across restarts',in:'Writes',out:'Durable reads',unlocks:'State that survives',tags:['physical'],prereq:['host'],next:['appdb','weights']},
    git:{eli5:'Version control for code — every change is a snapshot you can return to, compare, or share.',why:'Track code history',in:'File changes',out:'Commits',unlocks:'Collaboration, CI/CD, rollback',tags:['software'],aliases:['version control','commit history','source control'],next:['github']}
  };
  const generic=(id,name,role,cat)=>({id,name,role,cat,eli5:`${name} is the ${role} layer in this system.`,why:role,in:'Upstream input',out:'Downstream result',unlocks:'Adjacent capabilities',tags:[cat==='ai'||cat==='agent'?'ai':cat==='data'?'data':cat==='network'||cat==='cloud'?'network':'software']});
  const nodes=[];
  districts.forEach(d=>{
    const list=nodeSeeds[d.id]||[];
    list.forEach((s,i)=>{
      const cols=list.length>=5?3:(list.length===4?2:Math.min(3,list.length)), row=Math.floor(i/cols), col=i%cols, pad=14, gap=8, nw=(d.w-pad*2-(cols-1)*gap)/cols, nh=42;
      const x=d.x+pad+col*(nw+gap), y=d.y+58+row*(nh+7);
      const base=generic(s[0],s[1],s[3],d.id); Object.assign(base,{icon:s[2],district:d.id,x,y,w:nw,h:nh});
      if(roles[s[0]]) Object.assign(base,roles[s[0]]);
      nodes.push(base);
    });
  });
  const byId=Object.fromEntries(nodes.map(n=>[n.id,n]));
  const districtById=Object.fromEntries(districts.map(d=>[d.id,d]));
  const edges=[
    ['user','chat','calls'],['user','ide','calls'],['ide','git','reads'],['ide','modelServer','calls'],['chat','modelServer','calls'],['modelServer','inference','executes'],['inference','model','executes'],['model','weights','depends'],['inference','gpu','executes'],['inference','cpu','executes'],['git','github','data'],['github','cicd','calls'],['corpus','chunker','data'],['chunker','embedding','calls'],['embedding','vector','data'],['vector','retriever','data'],['retriever','model','data'],['agentLoop','model','calls'],['agentLoop','tool','calls'],['agentLoop','memory','data'],['agentLoop','mcp','calls'],['mcp','tool','calls'],['workflow','agentLoop','calls'],['queue','workflow','data'],['runtime','modelServer','executes'],['observe','modelServer','observes'],['observe','runtime','observes'],['secrets','github','security'],['cloudAi','agentLoop','calls'],['publicApi','mcp','calls'],
    ['corpus','finetune','data'],['finetune','weights','data'],['weights','quant','data'],['quant','inference','data'],['multimodal','model','depends'],['prompting','model','calls'],['prompting','agentLoop','data'],['evals','model','observes'],['evals','agentLoop','observes'],
    ['secrets','runtime','security'],['secrets','cicd','security'],['modelServer','cache','data'],['observe','agentLoop','observes'],['memory','vector','data'],['tool','shell','executes'],['tool','browser','executes'],['host','runtime','executes'],['chat','cloudAi','calls'],
    ['gateway','modelServer','network'],['secrets','gateway','security'],['chat','gateway','network']
  ].map((e,i)=>({id:'e'+i,a:e[0],b:e[1],type:e[2]}));
  const missions=[
    {id:'chatbot',name:'01 · Local Chatbot',path:['user','chat','modelServer','inference','gpu','model']},
    {id:'coding',name:'02 · AI Coding Assistant',path:['user','ide','git','shell','modelServer','model']},
    {id:'rag',name:'03 · Local RAG',path:['corpus','chunker','embedding','vector','retriever','modelServer','model']},
    {id:'mcp',name:'04 · MCP Agent',path:['user','agentLoop','mcp','tool','publicApi']},
    {id:'research',name:'05 · Autonomous Researcher',path:['user','agentLoop','browser','tool','memory','model']},
    {id:'automation',name:'06 · Automation Agent',path:['queue','workflow','agentLoop','tool','appdb']},
    {id:'ship',name:'07 · Ship an AI App',path:['ide','git','github','cicd','runtime']},
    {id:'scale',name:'08 · Scale AI Inference',path:['gateway','modelServer','inference','gpu','observe']},
    {id:'delivery',name:'09 · Secure Delivery Chain',path:['secrets','github','cicd','runtime','observe']},
    {id:'tune',name:'10 · Fine-tune a Model',path:['corpus','finetune','quant','weights','modelServer','evals']}
  ];
  const state={lens:'physical',depth:1,selected:null,selectedEdge:null,history:[],focus:false,trace:false,xray:false,xrayReturnDepth:null,highlightPath:[],mission:null,missionStep:-1,missionTimer:null,panX:0,panY:0,scale:1,linking:null,mechNode:null,mechStep:0};
  const user=(()=>{let d={pins:[],notes:{},links:[]};try{const raw=JSON.parse(localStorage.getItem('atlasUser')||'{}');if(Array.isArray(raw.pins))d.pins=raw.pins.filter(id=>typeof id==='string');if(raw.notes&&typeof raw.notes==='object')d.notes=raw.notes;if(Array.isArray(raw.links))d.links=raw.links.filter(l=>Array.isArray(l)&&l.length===2)}catch{}
    const save=()=>{try{localStorage.setItem('atlasUser',JSON.stringify(d))}catch{}};return{d,save}})();
  const escHtml=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  const svg=$('#worldSvg'), viewport=$('#viewport'), districtLayer=$('#districtLayer'), nodesLayer=$('#nodesLayer'), edgesLayer=$('#edgesLayer'), effectsLayer=$('#effectsLayer'), trustLayer=$('#trustLayer');
  const statusKey=$('#statusKey'), inspector=$('#inspector');
  function svgEl(tag,attrs={}){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
  function districtDecor(d,g){
    const cx=d.x+d.w/2,cy=d.y+d.h/2,pad=10;
    if(d.id==='shipyard'){
      const maxR=Math.min(d.w,d.h)/2-pad;
      [.9,.6,.32].forEach(f=>g.appendChild(svgEl('circle',{cx,cy,r:maxR*f,class:'ops-ring','pointer-events':'none'})));
      g.appendChild(svgEl('line',{x1:cx,y1:cy,x2:cx,y2:cy-maxR,class:'radar-sweep','pointer-events':'none'}));
    } else if(d.id==='cloudx'){
      const rx=d.w/2-pad,ry=d.h/2-pad*1.6;
      g.appendChild(svgEl('path',{d:`M ${cx-rx} ${cy} A ${rx} ${ry} 0 1 1 ${cx+rx} ${cy}`,class:'orbit-arc','pointer-events':'none'}));
    } else if(d.id==='iface'){
      ['#ff5d73','#ff9f43','#40e68b'].forEach((c,i)=>g.appendChild(svgEl('circle',{cx:d.x+16+i*14,cy:d.y+16,r:4,fill:c,opacity:.5,'pointer-events':'none'})));
    } else if(d.id==='serving'){
      g.appendChild(svgEl('rect',{x:d.x,y:d.y,width:d.w,height:d.h,rx:22,fill:'url(#thermalGradient)',opacity:.07,'pointer-events':'none'}));
      [[d.x+10,d.y+10],[d.x+d.w-10,d.y+10],[d.x+10,d.y+d.h-10],[d.x+d.w-10,d.y+d.h-10]].forEach(([x,y])=>g.appendChild(svgEl('circle',{cx:x,cy:y,r:3,class:'rivet','pointer-events':'none'})));
    } else if(d.id==='knowledge'){
      [10,20].forEach(inset=>g.appendChild(svgEl('rect',{x:d.x+inset,y:d.y+inset,width:d.w-inset*2,height:d.h-inset*2,rx:14,class:'vault-ring','pointer-events':'none'})));
    } else if(d.id==='agent'){
      const L=16;
      [[d.x+8,d.y+8,1,1],[d.x+d.w-8,d.y+8,-1,1],[d.x+8,d.y+d.h-8,1,-1],[d.x+d.w-8,d.y+d.h-8,-1,-1]].forEach(([x,y,sx,sy])=>g.appendChild(svgEl('path',{d:`M ${x} ${y+L*sy} V ${y} H ${x+L*sx}`,class:'reticle','pointer-events':'none'})));
    } else if(d.id==='foundation'){
      const L=7;
      [[d.x+10,d.y+10],[d.x+d.w-10,d.y+10],[d.x+10,d.y+d.h-10],[d.x+d.w-10,d.y+d.h-10]].forEach(([x,y])=>g.appendChild(svgEl('path',{d:`M ${x-L} ${y} H ${x+L} M ${x} ${y-L} V ${y+L}`,class:'cropmark','pointer-events':'none'})));
    } else if(d.id==='proving'){
      g.appendChild(svgEl('rect',{x:d.x+8,y:d.y+8,width:d.w-16,height:d.h-16,rx:16,class:'fence','pointer-events':'none'}));
    }
  }
  function districtCenter(id){const d=districtById[id];return d?{x:d.x+d.w/2,y:d.y+d.h/2}:{x:800,y:450}}
  function nodeCenter(id){const n=byId[id];if(n)return{x:n.x+n.w/2,y:n.y+n.h/2}; if(districtById[id])return districtCenter(id); return{x:800,y:450}}
  function renderMini(){const mini=$('#miniLayer');mini.innerHTML='';districts.forEach(d=>{const r=svgEl('rect',{x:d.x,y:d.y,width:d.w,height:d.h,rx:18,fill:'#0e1b2e',stroke:COLORS[d.id]||'#29405a','stroke-width':5,opacity:.85});mini.appendChild(r)})}
  function visibleForLens(obj){if(state.lens==='mission'){if(state.highlightPath.length===0||state.highlightPath.includes(obj.id))return true; if(districtById[obj.id])return state.highlightPath.some(h=>byId[h]?.district===obj.id); return false} const def=lensDefs[state.lens]; if(!def)return true; return (def.cats||[]).includes(obj.district||obj.id)||(obj.tags||[]).some(t=>(def.tags||[]).includes(t));}
  function renderMap(){
    districtLayer.innerHTML='';nodesLayer.innerHTML='';edgesLayer.innerHTML='';effectsLayer.innerHTML='';trustLayer.innerHTML='';
    if(state.lens==='security'){const b=svgEl('rect',{x:1170,y:15,width:410,height:140,rx:24,class:'trust-boundary'});trustLayer.appendChild(b);const t=svgEl('text',{x:1178,y:175,class:'zone-label'});t.textContent='CLOUD BOUNDARY · TRAFFIC CROSSING HERE LEAVES YOUR MACHINE';trustLayer.appendChild(t)}
    edges.forEach(e=>{const a=nodeCenter(e.a),b=nodeCenter(e.b);const dPath=`M ${a.x} ${a.y} C ${(a.x+b.x)/2} ${a.y}, ${(a.x+b.x)/2} ${b.y}, ${b.x} ${b.y}`; const crossing=byId[e.a]?.district!==byId[e.b]?.district; const path=svgEl('path',{d:dPath,class:`edge ${e.type}${crossing?' crossing':''}`,'data-edge':e.id,markerEnd:'url(#arrow)'}); if(state.highlightPath.includes(e.a)&&state.highlightPath.includes(e.b)){path.classList.add('active');path.setAttribute('marker-end','url(#arrowActive)')} if(state.trace&&state.selected&&(e.a===state.selected||e.b===state.selected)){path.classList.add('active');path.setAttribute('marker-end','url(#arrowActive)')} edgesLayer.appendChild(path); const hit=svgEl('path',{d:dPath,class:'edge-hit',tabindex:'0',role:'button','aria-label':`${e.type}: ${byId[e.a]?.name||e.a} to ${byId[e.b]?.name||e.b}`}); hit.addEventListener('click',()=>selectEdge(e.id));hit.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();selectEdge(e.id)}}); edgesLayer.appendChild(hit)});
    user.d.links.forEach((l,i)=>{const a=nodeCenter(l[0]),b=nodeCenter(l[1]);const dPath=`M ${a.x} ${a.y} C ${(a.x+b.x)/2} ${a.y}, ${(a.x+b.x)/2} ${b.y}, ${b.x} ${b.y}`;const path=svgEl('path',{d:dPath,class:'edge mylink','data-edge':'u'+i});edgesLayer.appendChild(path);const hit=svgEl('path',{d:dPath,class:'edge-hit',tabindex:'0',role:'button','aria-label':`your link: ${byId[l[0]]?.name||l[0]} to ${byId[l[1]]?.name||l[1]}`});hit.addEventListener('click',()=>selectEdge('u'+i));hit.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();selectEdge('u'+i)}});edgesLayer.appendChild(hit)});
    districts.forEach(d=>{
      const g=svgEl('g',{class:`district district-${d.id}`,'data-id':d.id,tabindex:'0',role:'button','aria-label':`${d.name}: ${d.sub}`});
      g.style.setProperty('--accent',COLORS[d.id]||'#29405a');
      if(state.selected===d.id)g.classList.add('highlight');
      if(state.focus&&state.selected&&state.selected!==d.id&&byId[state.selected]?.district!==d.id)g.classList.add('focusdim');
      if(state.depth>0 && state.selected!==d.id && !visibleForLens({...d,district:d.id,tags:d.tags}))g.classList.add('dim');
      const r=svgEl('rect',{x:d.x,y:d.y,width:d.w,height:d.h,class:'dbase'}); if(state.depth===0)r.style.strokeWidth='4';g.appendChild(r);
      const tex=svgEl('rect',{x:d.x,y:d.y,width:d.w,height:d.h,rx:22,class:'dtex','pointer-events':'none'});g.appendChild(tex);
      districtDecor(d,g);
      const ti=svgEl('text',{x:d.x+22,y:d.y+40,class:'dicon'});ti.textContent=d.icon;g.appendChild(ti);
      const tn=svgEl('text',{x:d.x+65,y:d.y+35,class:'dname'});tn.textContent=d.name;g.appendChild(tn);
      const ts=svgEl('text',{x:d.x+65,y:d.y+55,class:'dsub'});ts.textContent=d.sub;g.appendChild(ts);
      g.addEventListener('click',()=>select(d.id));g.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();select(d.id)}});districtLayer.appendChild(g)
    });
    if(state.depth>=2){nodes.forEach(n=>{
      const g=svgEl('g',{class:'node','data-id':n.id,'data-district':n.district,tabindex:'0',role:'button','aria-label':`${n.name}: ${n.role}`});
      if(state.selected===n.id)g.classList.add('selected');
      if(n.id!==state.selected && !visibleForLens(n)&&state.lens!=='mission')g.classList.add('dim');
      if(state.lens==='mission'&&state.highlightPath.length&&n.id!==state.selected&&!state.highlightPath.includes(n.id))g.classList.add('dim');
      if(state.focus&&state.selected&&n.id!==state.selected&&!isNeighbor(state.selected,n.id))g.classList.add('focusdim');
      const r=svgEl('rect',{x:n.x,y:n.y,width:n.w,height:n.h});g.appendChild(r);
      const catBar=svgEl('rect',{x:n.x,y:n.y,width:n.w,height:3,rx:1.5,class:'ncat'});catBar.style.fill=COLORS[n.district]||'#29405a';catBar.style.opacity='.55';g.appendChild(catBar);
      if(user.d.pins.includes(n.id)){const pm=svgEl('text',{x:n.x+n.w-14,y:n.y+14,class:'pinmark','pointer-events':'none'});pm.textContent='📌';g.appendChild(pm)}
      if(user.d.notes[n.id]){const nm2=svgEl('text',{x:n.x+n.w-(user.d.pins.includes(n.id)?28:14),y:n.y+14,class:'notemark','pointer-events':'none'});nm2.textContent='✎';g.appendChild(nm2)}
      const ic=svgEl('text',{x:n.x+10,y:n.y+25,class:'nicon'});ic.textContent=n.icon;g.appendChild(ic);
      const nm=svgEl('text',{x:n.x+35,y:n.y+23,class:'nname'});nm.textContent=n.name.length>22?n.name.slice(0,21)+'…':n.name;g.appendChild(nm);
      if(state.depth>=3){const rr=svgEl('text',{x:n.x+10,y:n.y+36,class:'nrole'});rr.textContent=n.role;g.appendChild(rr);}
      if(state.depth>=3){const impls=(n.implementations||[]); impls.slice(0,2).forEach((impl,i)=>{const label=impl.name,stab=stabilityOf(label);const ig=svgEl('g',{class:'impl'});const w=Math.min((n.w-23)/2,96),x=n.x+7+i*(w+5),y=n.y+n.h+5;const ir=svgEl('rect',{x,y,width:w,height:20});const it=svgEl('text',{x:x+6,y:y+13});it.textContent=label.length>15?label.slice(0,14)+'…':label;const dot=svgEl('circle',{cx:x+w-6,cy:y+6,r:2.5,class:`implstab implstab-${stab}`});ig.setAttribute('tabindex','0');ig.setAttribute('role','button');ig.setAttribute('aria-label',`${label} (${stab}), implementation of ${n.name}`);ig.append(ir,it,dot);const openImpl=ev=>{ev.stopPropagation?.();select(n.id);openCompare(n.id)};ig.addEventListener('click',openImpl);ig.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();openImpl(ev)}});nodesLayer.appendChild(ig)})}
      g.addEventListener('click',()=>select(n.id));g.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();select(n.id)}});nodesLayer.appendChild(g)
    })}
    if(state.highlightPath.length>1)drawPackets();
    updateTransform();updateHUD();
  }
  function isNeighbor(a,b){return edges.some(e=>(e.a===a&&e.b===b)||(e.a===b&&e.b===a))||byId[b]?.district===byId[a]?.district}
  function drawPackets(){for(let i=0;i<state.highlightPath.length-1;i++){const a=nodeCenter(state.highlightPath[i]),b=nodeCenter(state.highlightPath[i+1]);const c=svgEl('circle',{r:6,class:'packet'});const motion=svgEl('animateMotion',{dur:`${1.25+i*.08}s`,repeatCount:'indefinite',path:`M${a.x},${a.y} C${(a.x+b.x)/2},${a.y} ${(a.x+b.x)/2},${b.y} ${b.x},${b.y}`});c.appendChild(motion);effectsLayer.appendChild(c)}}
  function updateTransform(){viewport.setAttribute('transform',`translate(${state.panX} ${state.panY}) scale(${state.scale})`);const v=$('#miniViewport');const vw=1600/state.scale,vh=900/state.scale;v.setAttribute('width',Math.min(1584,vw));v.setAttribute('height',Math.min(884,vh));v.setAttribute('x',Math.max(8,170-state.panX/state.scale));v.setAttribute('y',Math.max(8,120-state.panY/state.scale))}
  function updateHUD(){
    const names=['Z0 WORLD','Z1 DISTRICT','Z2 CONCEPT','Z3 IMPLEMENTATION','Z4 MECHANISM','Z5 ENGINEERING'];$('#zoomLabel').textContent=names[state.depth];
    let c=`<button data-crumb-home="1">WORLD</button> › <button data-crumb-home="1"><b>REFERENCE LAB</b></button>`;
    if(state.selected){const n=byId[state.selected],d=districtById[state.selected]||districtById[n?.district]; if(d)c+=n?` › <button data-crumb-district="${d.id}">${d.name}</button>`:` › ${d.name}`; if(n)c+=` › <b>${n.name}</b>`} $('#crumbs').innerHTML=c;
    statusKey.innerHTML=`<span>◉ CONCEPT</span><span>▣ implementation appears at Z3</span>`;
    $$('.bottom .lens[data-lens]').forEach(b=>{const on=b.dataset.lens===state.lens;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});
    const moreIds=['software','performance','cost','learning'],moreOn=moreIds.includes(state.lens);const more=$('#moreLens');more.classList.toggle('active',moreOn);more.setAttribute('aria-pressed',String(moreOn));more.textContent=moreOn?`MORE · ${lensDefs[state.lens].label}`:'MORE ▾';
    syncHash();
  }
  let applyingHash=false,lastWrittenHash='',routerReady=false;
  function syncHash(){
    if(!routerReady||applyingHash)return;
    let h='';
    if(state.selected&&byId[state.selected])h=`#c/${state.selected}`;
    else if(state.selected&&districtById[state.selected])h=`#d/${state.selected}`;
    else if(state.missionTimer&&state.mission)h=`#m/${state.mission.id}`;
    else if(document.documentElement.classList.contains('atlas-unfiltered'))h='';
    else if(state.lens!=='physical')h=`#l/${state.lens}`;
    if((location.hash||'')!==h){if(h){lastWrittenHash=h;location.hash=h}else if(location.hash){lastWrittenHash='\x00';history.pushState('',document.title,location.pathname+location.search)}}
  }
  function applyHash(){
    const parts=(location.hash||'').replace(/^#/,'').split('/');
    const kind=parts[0],id=parts[1];
    if(!kind)return;
    applyingHash=true;
    try{
      if(kind==='c'&&byId[id])select(id);
      else if(kind==='d'&&districtById[id])select(id);
      else if(kind==='m'&&missions.some(m=>m.id===id))startMission(id);
      else if(kind==='l'&&id==='all')$('#allLens')?.click();
      else if(kind==='l'&&lensDefs[id]){const b=document.querySelector(`.bottom .lens[data-lens="${id}"]`);if(b)b.click();else{stopMission(true);state.lens=id;renderMap();renderInspector()}}
    }finally{applyingHash=false}
  }
  window.addEventListener('hashchange',()=>{if((location.hash||'')===lastWrittenHash){lastWrittenHash='\x00';return}applyHash()});
  window.addEventListener('load',()=>{if(location.hash)applyHash();routerReady=true;syncHash()});
  function select(id){
    if(state.linking&&byId[id]&&id!==state.linking){const a=state.linking,b=id;const dup=user.d.links.some(l=>(l[0]===a&&l[1]===b)||(l[0]===b&&l[1]===a));if(!dup){user.d.links.push([a,b]);user.save();toast(`Linked ${byId[a]?.name} ↔ ${byId[b]?.name}`)}else toast('Those concepts are already linked.');state.linking=null}
    else if(state.linking&&id===state.linking){state.linking=null;toast('Link cancelled.')}
    if(state.selected!==id||state.selectedEdge)state.history.push({selected:state.selected,selectedEdge:state.selectedEdge,depth:state.depth,lens:state.lens,panX:state.panX,panY:state.panY});state.selected=id;state.selectedEdge=null;state.focus=false;state.trace=false;state.xray=false; if(districtById[id]){if(state.depth<2)state.depth=2;state.scale=[.88,.96,1.02,1.08,1.13,1.18][state.depth];const d=districtById[id];state.panX=800-state.scale*(d.x+d.w/2);state.panY=450-state.scale*(d.y+d.h/2)} if(byId[id]&&state.depth<2)state.depth=2; renderMap();renderInspector(); if(innerWidth<900)inspector.classList.add('open')}
  function renderInspector(){
    if(state.selectedEdge){renderEdgeInspector();return}
    const id=state.selected;if(!id){renderWelcome();return}
    const n=byId[id]; if(!n){const d=districtById[id];$('#insEyebrow').textContent='DISTRICT';$('#insIcon').textContent=d.icon;$('#insTitle').textContent=d.name;$('#insPath').textContent=`World → ${d.name}`;$('#insBody').innerHTML=`<div class="eli5"><b>ELI5</b><p>${d.sub}. This region groups concepts that solve the same class of problem while preserving their position across every lens.</p></div><div class="section"><h3>Zoom deeper</h3><div class="chips"><button class="chip" data-go-depth="2">Z2 · reveal concepts</button><button class="chip" data-go-depth="3">Z3 · reveal implementations</button></div></div>`;renderActions(null);return}
    $('#insEyebrow').textContent='CONCEPT';$('#insIcon').textContent=n.icon;$('#insTitle').textContent=n.name;$('#insPath').textContent=`World → ${districtById[n.district].name} → ${n.name}`;
    let html=`<div class="eli5"><b>ELI5</b><p>${n.eli5}</p></div><div class="six"><div class="fact"><b>WHY?</b><span>${n.why}</span></div><div class="fact"><b>WHERE?</b><span>${districtById[n.district].name}</span></div><div class="fact"><b>IN?</b><span>${n.in}</span></div><div class="fact"><b>OUT?</b><span>${n.out}</span></div><div class="fact"><b>UNLOCKS?</b><span>${n.unlocks}</span></div><div class="fact"><b>STATUS</b><span>Reference concept</span></div></div>`;
    if(state.xray||state.depth>=4)html+=mechanismHtml(n);
    if(state.depth>=5)html+=engineeringHtml(n);
    if(n.implementations?.length){html+=`<div class="section"><h3>Reference implementations</h3><div class="chips">${n.implementations.map(i=>`<span class="chip">${i.name}</span>`).join('')}</div></div>`}
    const pinned=user.d.pins.includes(n.id);html+=`<div class="section"><h3>📌 My layer</h3><div class="chips"><button class="chip" data-pin="${n.id}">${pinned?'Unpin':'Pin'}</button><button class="chip" data-link-start="${n.id}">${state.linking===n.id?'Cancel link':'Link to…'}</button></div><textarea class="mynote" data-note="${n.id}" placeholder="Your note on this concept (saved locally)…">${escHtml(user.d.notes[n.id]||'')}</textarea></div>`;
    const src=n.implementations?.find(i=>i.source)?.source;html+=`<div class="section source"><b>REFERENCE HYGIENE</b><br/>Concept layer: general knowledge, not a single citable source. Implementation layer: time-sensitive — open Compare for each tool's stability tag and verified date.${src?` <a href="${src}" target="_blank" rel="noreferrer">Official source ↗</a>`:''}</div>`;
    $('#insBody').innerHTML=html;renderActions(n)
  }
  function selectEdge(eid){if(state.selectedEdge!==eid)state.history.push({selected:state.selected,selectedEdge:state.selectedEdge,depth:state.depth,lens:state.lens});state.selected=null;state.selectedEdge=eid;renderMap();renderInspector();if(innerWidth<900)inspector.classList.add('open')}
  function renderEdgeInspector(){
    if(/^u\d+$/.test(state.selectedEdge||'')){const i=+state.selectedEdge.slice(1),l=user.d.links[i];if(!l){renderWelcome();return}const a=byId[l[0]],b=byId[l[1]];$('#insEyebrow').textContent='MY LINK';$('#insIcon').textContent='🔗';$('#insTitle').textContent='Your connection';$('#insPath').textContent=`${a?.name||l[0]} ↔ ${b?.name||l[1]}`;$('#insBody').innerHTML=`<div class="eli5"><b>YOUR LAYER</b><p>You drew this connection between <strong>${a?.name||l[0]}</strong> and <strong>${b?.name||l[1]}</strong>. It lives only in this browser.</p></div><div class="six"><div class="fact"><b>FROM</b><span>${a?.name||l[0]}</span></div><div class="fact"><b>TO</b><span>${b?.name||l[1]}</span></div></div><div class="section"><div class="chips"><button class="chip" data-go-node="${l[0]}">Go to ${a?.name||l[0]}</button><button class="chip" data-go-node="${l[1]}">Go to ${b?.name||l[1]}</button><button class="chip" data-remove-link="${i}">🗑 Remove link</button></div></div>`;renderActions(null);return}
    const e=edges.find(x=>x.id===state.selectedEdge);if(!e){renderWelcome();return}const a=byId[e.a],b=byId[e.b];const labels={calls:'CALLS',data:'SENDS DATA',depends:'DEPENDS ON',executes:'EXECUTES',reads:'READS',security:'AUTH / TRUST',network:'NETWORK PATH',observes:'OBSERVES'};$('#insEyebrow').textContent='RELATIONSHIP';$('#insIcon').textContent='↗';$('#insTitle').textContent=labels[e.type]||e.type.toUpperCase();$('#insPath').textContent=`${a?.name||e.a} → ${b?.name||e.b}`;$('#insBody').innerHTML=`<div class="eli5"><b>WHAT THIS LINE MEANS</b><p><strong>${a?.name||e.a}</strong> ${relationshipPhrase(e.type)} <strong>${b?.name||e.b}</strong>. Lines are first-class reference objects, not decorative connectors.</p></div><div class="six"><div class="fact"><b>FROM</b><span>${a?.name||e.a}</span></div><div class="fact"><b>TO</b><span>${b?.name||e.b}</span></div><div class="fact"><b>TYPE</b><span>${labels[e.type]||e.type}</span></div><div class="fact"><b>LENS</b><span>${lensDefs[state.lens].label}</span></div></div><div class="section"><h3>Visual grammar</h3><div class="chips"><span class="chip">solid = call/control</span><span class="chip">dashed = data/trust</span><span class="chip">blue = network</span><span class="chip">cyan dash-dot = observes</span></div></div>`;renderActions(null)}
  function relationshipPhrase(type){return({calls:'calls',data:'sends data to',depends:'depends on',executes:'executes work on',reads:'reads from',security:'crosses a security/auth boundary toward',network:'routes network traffic through',observes:'collects telemetry from'})[type]||'connects to'}
  const PROVENANCE_DATE='2026-08-09';
  const STABILITY={
    Ollama:'stable','llama.cpp':'evolving',vLLM:'evolving','sentence-transformers':'stable',Qdrant:'stable',Chroma:'evolving',pgvector:'stable',
    LlamaIndex:'volatile',LangChain:'volatile',MCP:'evolving','Claude Agent SDK':'evolving',LangGraph:'volatile',
    Docker:'stable',Caddy:'stable',"Let's Encrypt":'stable',OpenTelemetry:'evolving',Prometheus:'stable',Grafana:'stable',
    GitHub:'stable',Forgejo:'evolving','GitHub Actions':'stable','GitLab CI':'stable',CUDA:'stable',ROCm:'evolving',
    'Open WebUI':'evolving',PostgreSQL:'stable',SQLite:'stable',Redis:'stable',Valkey:'evolving',n8n:'evolving',
    'Apache Airflow':'stable',NATS:'stable',RabbitMQ:'stable',Vaultwarden:'evolving','HashiCorp Vault':'stable',
    'Hugging Face PEFT':'evolving',Unsloth:'volatile','GGUF (llama.cpp)':'evolving',bitsandbytes:'evolving',
    Whisper:'stable','Stable Diffusion':'evolving','Claude prompting guide':'evolving','lm-evaluation-harness':'evolving',promptfoo:'evolving',
    Cursor:'evolving','Claude Code':'evolving',Playwright:'stable','Anthropic API':'evolving','OpenAI API':'evolving',RunPod:'evolving',Lambda:'evolving'
  };
  const stabilityOf=name=>STABILITY[name]||'unrated';
  const STAB_LABEL={stable:'🟢 STABLE',evolving:'🟠 EVOLVING',volatile:'🔴 VOLATILE',unrated:'⚪ UNRATED'};
  const mechanisms={
    mcp:[{id:'user',note:'You give the agent a goal.'},{id:'agentLoop',note:'The agent decides it needs an external capability.'},{id:'mcp',note:'MCP exposes tools/resources through one standard protocol.'},{id:'tool',note:'The tool executes the actual action.'},{id:'publicApi',note:'The result comes back from a real external system.'}],
    retriever:[{id:'corpus',note:'Your documents are the source of truth.'},{id:'chunker',note:'Split into small, retrievable pieces.'},{id:'embedding',note:'Each chunk becomes a vector.'},{id:'vector',note:'Vectors are indexed for similarity search.'},{id:'retriever',note:'Your question finds the closest matching chunks.'},{id:'modelServer',note:'Matched chunks are injected as context.'},{id:'model',note:'The model answers using only what it was given.'}],
    modelServer:[{id:'chat',note:'App sends a request over HTTP.'},{id:'modelServer',note:'The API receives and queues it.'},{id:'inference',note:'The inference engine prepares the forward pass.'},{id:'gpu',note:'Parallel math executes on the accelerator.'},{id:'model',note:'Tokens generate one at a time and stream back.'}],
    runtime:[{id:'ide',note:'You build and package a container image.'},{id:'runtime',note:'The container runtime starts an isolated process.'},{id:'modelServer',note:'Your service runs, networked and mounted.'},{id:'observe',note:'Logs and metrics flow out for visibility.'}],
    gateway:[{id:'chat',note:'A client requests your public domain.'},{id:'gateway',note:'TLS handshake encrypts the session; hostname routes it.'},{id:'modelServer',note:'The internal service receives the decrypted request.'},{id:'inference',note:'The request reaches the model, safely, from anywhere.'}],
    finetune:[{id:'corpus',note:'Your examples become the training signal.'},{id:'finetune',note:'LoRA trains small adapter layers, not the whole model.'},{id:'weights',note:'Adapted weights capture your specialization.'},{id:'quant',note:'Compressed to fit real hardware.'},{id:'modelServer',note:'Serves your specialized model like any other.'}],
    agentLoop:[{id:'user',note:'You give the agent a goal.'},{id:'agentLoop',note:'It observes the situation and decides the next action.'},{id:'model',note:'The model reasons about what to do.'},{id:'tool',note:'It acts using a real tool.'},{id:'memory',note:'The result is remembered — then it loops.'}],
    cicd:[{id:'github',note:'A push or pull request triggers the pipeline.'},{id:'cicd',note:'Automated test and build steps run.'},{id:'runtime',note:'The build is packaged into a container.'},{id:'observe',note:'You watch it deploy and verify it’s healthy.'}],
    queue:[{id:'queue',note:'A producer publishes an event, ordered and durable.'},{id:'workflow',note:'The workflow engine picks it up when ready.'},{id:'agentLoop',note:'Work triggers an agent action downstream.'}],
    embedding:[{id:'tokenizer',note:'Text is split into tokens the model understands.'},{id:'embedding',note:'A forward pass turns tokens into one dense vector.'},{id:'vector',note:'Stored or compared by distance to find similar meaning.'}],
    vector:[{id:'embedding',note:'A query vector arrives.'},{id:'vector',note:'An approximate nearest-neighbor index searches fast, not exhaustively.'},{id:'retriever',note:'Top-K closest matches return with their original content.'}]
  };
  function mechanismHtml(n){
    const steps=mechanisms[n.id];
    if(!steps)return `<div class="section"><h3>🔬 Mechanism</h3><div class="eli5"><p>Trace the upstream inputs, execution step, and downstream outputs on the map.</p></div></div>`;
    if(state.mechNode!==n.id){state.mechNode=n.id;state.mechStep=0}
    const i=Math.max(0,Math.min(state.mechStep,steps.length-1)),s=steps[i],node=byId[s.id];
    const dots=steps.map((_,idx)=>`<span class="mechdot ${idx<=i?'on':''}"></span>`).join('');
    return `<div class="section"><h3>🔬 Mechanism · step ${i+1} of ${steps.length}</h3><div class="eli5"><b>${node?.icon||''} ${node?.name||s.id}</b><p>${s.note}</p></div><div class="mechdots">${dots}</div><div class="chips mech-nav"><button class="chip" data-mech-prev ${i===0?'disabled':''}>◀ Prev</button><button class="chip" data-mech-next ${i===steps.length-1?'disabled':''}>Next ▶</button></div></div>`;
  }
  function engineeringHtml(n){return `<div class="section"><h3>🧰 Engineering depth</h3><div class="chips"><span class="chip">process</span><span class="chip">port/protocol</span><span class="chip">API contract</span><span class="chip">config/env</span><span class="chip">runtime</span><span class="chip">source subsystem</span></div><p class="source" style="margin-top:8px">Z5 is intentionally implementation-oriented. Exact values belong to implementation entries, not the permanent concept node.</p></div>`}
  function renderWelcome(){
    $('#insEyebrow').textContent='START HERE';$('#insIcon').textContent='🗺️';$('#insTitle').textContent='The Whole Lab';$('#insPath').textContent='World view · stable geography';
    $('#insBody').innerHTML=`<div class="eli5"><b>TOP-DOWN</b><p>Start with the whole AI landscape visible. Click a district, zoom to concepts, then reveal real tools only when you need them.</p></div><div class="six"><div class="fact"><b>WORLD</b><span>Complete reference universe</span></div><div class="fact"><b>LENS</b><span>${lensDefs[state.lens].label}</span></div><div class="fact"><b>ZOOM</b><span>${$('#zoomLabel').textContent}</span></div><div class="fact"><b>RULE</b><span>Position never changes</span></div></div><div class="section"><h3>Start a guided mission</h3><div class="chips"><button class="chip" data-go-mission="chatbot">▶ Local Chatbot</button><button class="chip" data-go-mission="rag">▶ Local RAG</button><button class="chip" data-go-mission="mcp">▶ MCP Agent</button></div></div>${user.d.pins.length?`<div class="section"><h3>📌 Pinned</h3><div class="chips">${user.d.pins.slice(0,8).map(id=>`<button class="chip" data-go-node="${id}">${byId[id]?.icon||''} ${byId[id]?.name||id}</button>`).join('')}</div></div>`:''}<div class="section"><h3>Try this</h3><div class="chips"><button class="chip" data-go-search="MCP">Search MCP</button><button class="chip" data-go-builder="1">Open Builder</button></div></div>`;renderActions(null)
  }
  function renderActions(n){
    const defs=[['focus','👁','FOCUS'],['trace','⚡','TRACE'],['show','▶','SHOW ME'],['xray','🔬','X-RAY'],['compare','⚔','COMPARE'],['build','🧩','BUILD WITH'],['learn','📚','LEARN']];
    $('#actionRail').innerHTML=defs.map(([id,ic,lab])=>{const disabled=(!n&&['focus','trace','show','xray','compare','learn'].includes(id))||(id==='compare'&&n&&!(n.implementations?.length));return `<button data-action="${id}" ${disabled?'disabled':''} class="${state[id]?'active':''}">${ic}<br>${lab}</button>`}).join('');
    $$('#actionRail button').forEach(b=>b.addEventListener('click',()=>handleAction(b.dataset.action,n)))
  }
  function handleAction(action,n){
    if(action==='focus'){state.focus=!state.focus;renderMap();renderInspector()}
    if(action==='trace'){state.trace=!state.trace;renderMap();renderInspector()}
    if(action==='show')showMechanism(n)
    if(action==='xray'){if(!state.xray){state.xrayReturnDepth=state.depth;state.xray=true;state.depth=Math.max(state.depth,4)}else{state.xray=false;if(state.xrayReturnDepth!==null)state.depth=state.xrayReturnDepth;state.xrayReturnDepth=null}renderMap();renderInspector()}
    if(action==='compare')openCompare(n.id)
    if(action==='build')openBuilder(n?.id)
    if(action==='learn')openLearn(n)
  }
  function setMissionButton(playing){const b=$('#missionPlay');b.textContent=playing?'Ⅱ':'▶';b.setAttribute('aria-label',playing?'Pause mission':'Play mission')}
  function stopMission(clearPath=true){if(state.missionTimer){clearInterval(state.missionTimer);state.missionTimer=null}setMissionButton(false);if(clearPath){state.highlightPath=[];const t=$('#toast');clearTimeout(t._to);t.classList.remove('show')}state.missionStep=-1}
  function bestLensFor(n){const t=n?.tags||[];if(t.includes('ai'))return 'ai';if(t.includes('network'))return 'network';if(t.includes('data'))return 'data';if(t.includes('security'))return 'security';if(t.includes('performance'))return 'performance';return 'physical'}
  function showMechanism(n){stopMission(false);const steps=mechanisms[n.id];state.highlightPath=steps?steps.map(s=>s.id):[n.id,...edges.filter(e=>e.a===n.id).slice(0,3).map(e=>e.b)];state.lens='mission';renderMap();toast(`▶ SHOW ME: ${n.name} · follow the bright path`)}
  function openCompare(id){const n=byId[id];const impls=n?.implementations;if(!impls?.length){toast('Comparison is available when a concept has multiple reference implementations.');return}$('#modalTitle').textContent=`⚔ Compare · ${n.name}`;const accent=COLORS[n.district]||'#29405a';$('#modalBody').innerHTML=`<p class="stab-legend">🟢 stable — mature, unlikely to break · 🟠 evolving — active development, check before pinning · 🔴 volatile — expect breaking changes</p><div class="compare-grid" style="--accent:${accent}">${impls.map(i=>{const stab=stabilityOf(i.name);return `<div class="compare-card"><h3>${i.name}</h3><div class="kv"><b>ROLE</b><span>${i.role}</span></div><div class="kv"><b>COMPLEXITY</b><span>${i.complexity}</span></div><div class="kv"><b>SCALE</b><span>${i.scale}</span></div><div class="kv"><b>HARDWARE</b><span>${i.hardware}</span></div><div class="kv"><b>BEST FOR</b><span>${i.ideal}</span></div><div class="kv"><b>TRADEOFF</b><span>${i.tradeoff}</span></div><div class="kv"><b>STABILITY</b><span class="stab-${stab}">${STAB_LABEL[stab]}</span></div><div class="kv"><b>VERIFIED</b><span>${PROVENANCE_DATE}</span></div><div class="source"><a href="${i.source}" target="_blank" rel="noreferrer">Official source ↗</a></div></div>`}).join('')}</div>`;openModal()}
  const builderParts=[['model','🧠 Model'],['tool','🛠 Tool'],['loop','🔁 Loop'],['memory','💾 Memory'],['mcp','🔌 MCP'],['retriever','🔎 Retriever'],['vector','🔢 Vector Store'],['workflow','🏭 Workflow']];let builderSet=new Set(['model']);
  function openBuilder(seed){if(seed&&['model','tool','agentLoop','memory','mcp','retriever','vector','workflow'].includes(seed))builderSet.add(seed==='agentLoop'?'loop':seed);$('#modalTitle').textContent='🧩 System Builder';renderBuilder();openModal()}
  function renderBuilder(){const partAccent=id=>COLORS[byId[id==='loop'?'agentLoop':id]?.district]||'#29405a';const parts=builderParts.map(([id,label])=>`<button class="partbtn ${builderSet.has(id)?'on':''}" data-part="${id}" style="--accent:${partAccent(id)}"><span>${label}</span><b>${builderSet.has(id)?'ON':'+'}</b></button>`).join('');const flow=[...builderSet].map(id=>`<span class="bnode" style="--accent:${partAccent(id)}">${builderParts.find(x=>x[0]===id)?.[1]||id}</span>`).join('<span class="barrow">→</span>');let cap='Prompted model';if(builderSet.has('model')&&builderSet.has('tool'))cap='Tool-using AI';if(builderSet.has('model')&&builderSet.has('tool')&&builderSet.has('loop'))cap='Agent';if(cap==='Agent'&&builderSet.has('memory'))cap='Stateful Agent';if(builderSet.has('model')&&builderSet.has('retriever')&&builderSet.has('vector'))cap='RAG-capable AI';if(builderSet.has('model')&&builderSet.has('tool')&&builderSet.has('loop')&&builderSet.has('mcp'))cap='MCP-enabled Agent';if(builderSet.has('workflow')&&builderSet.has('loop'))cap='Automated Agent Workflow';$('#modalBody').innerHTML=`<div class="builder-grid"><div class="builder-parts">${parts}</div><div class="builder-canvas"><div class="eyebrow">YOUR MACHINE</div><h2 style="margin:8px 0 14px">${cap}</h2><div class="builder-flow">${flow||'<span class="source">Choose components.</span>'}</div><div class="capability"><b>CAPABILITY UNLOCKED</b><p style="margin:5px 0 0;color:var(--muted);font-size:13px">${cap}. Add or remove components and watch the system identity change.</p></div><button class="chip" id="builderShowMap" ${builderSet.size<2?'disabled':''} style="margin-top:12px">🗺️ Show this composition on the map</button></div></div>`;$$('.partbtn').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.part;builderSet.has(id)?builderSet.delete(id):builderSet.add(id);renderBuilder()}));$('#builderShowMap')?.addEventListener('click',()=>{const path=[...builderSet].map(id=>id==='loop'?'agentLoop':id).filter(id=>byId[id]);if(path.length<2)return;stopMission(true);state.highlightPath=path;state.lens='mission';closeModal();renderMap();renderInspector();toast('Showing your composition on the map')})}
  function openLearn(n){const step=id=>byId[id]?`<button data-go-node="${id}">${byId[id].name}</button>`:`<span>${id}</span>`;const pre=(n.prereq||[]),next=(n.next||[]);$('#modalTitle').textContent=`📚 Learning Path · ${n.name}`;$('#modalBody').innerHTML=`<div class="eyebrow">PREREQUISITES → CURRENT → UNLOCKS</div><div class="learn-chain" style="margin-top:14px">${pre.map(step).join('<b>→</b>')}${pre.length?'<b>→</b>':''}<span class="current">${n.name}</span>${next.length?'<b>→</b>':''}${next.map(step).join('<b>→</b>')}</div><div class="eli5" style="margin-top:18px"><b>PATTERN</b><p>Learn the dependency immediately before the concept, then build one tiny working path that uses it. Every step above is clickable — travel the chain.</p></div>`;openModal()}
  function openModal(){$('#overlay').classList.add('open')}function closeModal(){$('#overlay').classList.remove('open')}
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._to);t._to=setTimeout(()=>t.classList.remove('show'),2400)}
  function scoreQuery(q){return nodes.map(n=>{const hay=[n.name,n.role,n.eli5,...(n.aliases||[]),...(n.implementations||[]).map(i=>i.name)].join(' ').toLowerCase();let s=0;if(hay===q)s=100;if(n.name.toLowerCase()===q)s=95;if((n.aliases||[]).some(a=>a===q))s=90;if(hay.includes(q))s=Math.max(s,60);q.split(/\s+/).forEach(w=>{if(w.length>2&&hay.includes(w))s+=5});return{n,s}}).sort((a,b)=>b.s-a.s)}
  function search(){const q=$('#searchInput').value.trim().toLowerCase();if(!q)return;closeSearchMenu();stopMission(true);let scored=scoreQuery(q);const hit=scored[0];if(!hit||hit.s<5){toast(`No strong match for “${q}”. Try a concept, product, or goal.`);return}state.depth=Math.max(state.depth,2);select(hit.n.id);state.lens=bestLensFor(hit.n);renderMap();renderInspector();toast(`You searched “${q}” → ${hit.n.name}`)}
  let menuIdx=-1;
  function renderSearchMenu(){const q=$('#searchInput').value.trim().toLowerCase();const menu=$('#searchMenu');if(!q){closeSearchMenu();return}const hits=scoreQuery(q).filter(x=>x.s>=5).slice(0,6);if(!hits.length){closeSearchMenu();return}menuIdx=-1;menu.innerHTML=hits.map(x=>`<button role="option" id="sm-${x.n.id}" data-sm="${x.n.id}">${x.n.icon} <b>${x.n.name}</b><span>${districtById[x.n.district].name}</span></button>`).join('');menu.hidden=false;$('#searchInput').setAttribute('aria-expanded','true')}
  function closeSearchMenu(){const menu=$('#searchMenu');if(!menu||menu.hidden)return;menu.hidden=true;menu.innerHTML='';menuIdx=-1;$('#searchInput').setAttribute('aria-expanded','false');$('#searchInput').removeAttribute('aria-activedescendant')}
  function searchKeydown(e){const menu=$('#searchMenu');const opts=menu&&!menu.hidden?[...menu.querySelectorAll('button')]:[];
    if((e.key==='ArrowDown'||e.key==='ArrowUp')&&opts.length){e.preventDefault();menuIdx=e.key==='ArrowDown'?(menuIdx+1)%opts.length:(menuIdx-1+opts.length)%opts.length;opts.forEach((o,i)=>o.classList.toggle('active',i===menuIdx));$('#searchInput').setAttribute('aria-activedescendant',opts[menuIdx].id)}
    else if(e.key==='Escape')closeSearchMenu();
    else if(e.key==='Enter'){if(menuIdx>=0&&opts[menuIdx])$('#searchInput').value=byId[opts[menuIdx].dataset.sm]?.name||$('#searchInput').value;search()}}
  function playMission(){const id=$('#missionSelect').value,m=missions.find(x=>x.id===id);if(state.missionTimer){stopMission(false);toast('Mission paused.');return}state.mission=m;state.lens='mission';state.highlightPath=[];state.missionStep=-1;setMissionButton(true);const tick=()=>{state.missionStep++;if(state.missionStep>=m.path.length){clearInterval(state.missionTimer);state.missionTimer=null;setMissionButton(false);toast(`Mission complete: ${m.name}`);openMissionSummary(m);return}state.highlightPath=m.path.slice(0,state.missionStep+1);renderMap();const n=byId[m.path[state.missionStep]];toast(`${state.missionStep+1}/${m.path.length} · ${n?.name||m.path[state.missionStep]}`)};tick();state.missionTimer=setInterval(tick,1100)}
  function openMissionSummary(m){$('#modalTitle').textContent=`🏁 ${m.name} · What you need`;$('#modalBody').innerHTML=`<div class="eyebrow">CONCEPTS TRAVERSED → TOOLS TO EXPLORE</div>${m.path.map(id=>{const n=byId[id];if(!n)return '';const impls=(n.implementations||[]).map(i=>`<a class="chip" href="${i.source}" target="_blank" rel="noreferrer">${i.name} ↗</a>`).join('');return `<div class="section"><h3>${n.icon} ${n.name}</h3><div class="chips"><button class="chip" data-go-node="${n.id}">View on map</button>${impls||'<span class="chip unknown">concept — no tool needed</span>'}</div></div>`}).join('')}<div class="eli5" style="margin-top:14px"><b>NEXT</b><p>Work through the tools above in path order — each link is an official source. Re-run the mission anytime and follow the packets.</p></div>`;openModal()}
  function setDepth(d){state.depth=Math.max(0,Math.min(5,d));state.scale=[.88,.96,1.02,1.08,1.13,1.18][state.depth];renderMap();renderInspector()}
  function home(){stopMission(true);state.selected=null;state.selectedEdge=null;state.history=[];state.focus=false;state.trace=false;state.xray=false;state.xrayReturnDepth=null;state.highlightPath=[];state.lens='physical';state.panX=0;state.panY=0;state.scale=.96;state.depth=1;renderMap();renderWelcome();inspector.classList.remove('open')}
  const pointers=new Map();let pinching=false;
  const SCALE_TABLE=[.88,.96,1.02,1.08,1.13,1.18];
  function depthFromScale(s){let best=0;for(let i=1;i<SCALE_TABLE.length;i++){if(Math.abs(s-SCALE_TABLE[i])<Math.abs(s-SCALE_TABLE[best]))best=i}return best}
  svg.addEventListener('pointerdown',e=>{if(e.target.closest?.('.node,.district,.impl'))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});try{svg.setPointerCapture(e.pointerId)}catch{}});
  svg.addEventListener('pointermove',e=>{
    if(!pointers.has(e.pointerId))return;
    if(pointers.size===2){
      const other=[...pointers.entries()].find(([id])=>id!==e.pointerId);
      if(!other)return;
      const prev=pointers.get(e.pointerId),o=other[1];
      const prevDist=Math.hypot(prev.x-o.x,prev.y-o.y),newDist=Math.hypot(e.clientX-o.x,e.clientY-o.y);
      if(prevDist>0&&newDist>0){
        const ratio=newDist/prevDist,next=Math.max(.6,Math.min(2.5,state.scale*ratio)),applied=next/state.scale;
        const rect=svg.getBoundingClientRect(),sx=1600/rect.width,sy=900/rect.height;
        const midX=((e.clientX+o.x)/2-rect.left)*sx,midY=((e.clientY+o.y)/2-rect.top)*sy;
        state.panX=midX-(midX-state.panX)*applied;state.panY=midY-(midY-state.panY)*applied;
        state.scale=next;pinching=true;updateTransform();
      }
      pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
    } else if(pointers.size===1){
      const prev=pointers.get(e.pointerId);
      state.panX+=e.clientX-prev.x;state.panY+=e.clientY-prev.y;
      pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});updateTransform();
    }
  });
  const endPointer=e=>{pointers.delete(e.pointerId);if(pinching&&pointers.size<2){pinching=false;state.depth=depthFromScale(state.scale);renderMap();renderInspector()}};
  svg.addEventListener('pointerup',endPointer);svg.addEventListener('pointercancel',endPointer);
  function goBack(){stopMission(true);state.xrayReturnDepth=null;const h=state.history.pop();if(!h){home();return}state.selected=h.selected;state.selectedEdge=h.selectedEdge;state.depth=h.depth;state.lens=h.lens;if(h.panX!==undefined){state.panX=h.panX;state.panY=h.panY}state.scale=[.88,.96,1.02,1.08,1.13,1.18][state.depth];state.focus=false;state.trace=false;state.xray=false;state.highlightPath=[];renderMap();renderInspector()}
  $('#zoomIn').addEventListener('click',()=>setDepth(state.depth+1));$('#zoomOut').addEventListener('click',()=>setDepth(state.depth-1));$('#backBtn').addEventListener('click',goBack);$('#homeBtn').addEventListener('click',home);$('#searchBtn').addEventListener('click',search);$('#searchInput').addEventListener('keydown',searchKeydown);$('#searchInput').addEventListener('input',renderSearchMenu);$('#searchInput').addEventListener('blur',()=>setTimeout(closeSearchMenu,150));$('#searchMenu').addEventListener('pointerdown',e=>e.preventDefault());$('#searchMenu').addEventListener('click',e=>{const b=e.target.closest('button[data-sm]');if(!b)return;$('#searchInput').value=byId[b.dataset.sm]?.name||'';$('#searchBtn').click()});
  function startMission(id){stopMission(true);$('#missionSelect').value=id;inspector.classList.remove('open');playMission()}
  $('#crumbs').addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.crumbHome)home();else if(t.dataset.crumbDistrict)select(t.dataset.crumbDistrict)});
  $('#insBody').addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.goMission)startMission(t.dataset.goMission);else if(t.dataset.goSearch){$('#searchInput').value=t.dataset.goSearch;search()}else if(t.dataset.goBuilder)openBuilder();else if(t.dataset.goDepth)setDepth(+t.dataset.goDepth);else if(t.dataset.goNode)select(t.dataset.goNode);else if(t.dataset.pin){const id=t.dataset.pin,i=user.d.pins.indexOf(id);i>=0?user.d.pins.splice(i,1):user.d.pins.push(id);user.save();renderMap();renderInspector()}else if(t.dataset.linkStart){const id=t.dataset.linkStart;state.linking=state.linking===id?null:id;renderInspector();toast(state.linking?`Linking from ${byId[id]?.name} — click another concept to connect.`:'Link cancelled.')}else if(t.dataset.removeLink!==undefined){user.d.links.splice(+t.dataset.removeLink,1);user.save();state.selectedEdge=null;renderMap();renderWelcome()}else if(t.dataset.mechNext!==undefined||t.dataset.mechPrev!==undefined){const steps=mechanisms[state.mechNode];if(!steps)return;stopMission(true);state.mechStep=Math.max(0,Math.min(state.mechStep+(t.dataset.mechNext!==undefined?1:-1),steps.length-1));state.highlightPath=steps.slice(0,state.mechStep+1).map(s=>s.id);state.lens='mission';renderMap();renderInspector()}});
  $('#insBody').addEventListener('input',e=>{const t=e.target;if(!t.matches('textarea[data-note]'))return;const id=t.dataset.note,v=t.value.trim();if(v)user.d.notes[id]=t.value;else delete user.d.notes[id];user.save()});
  $('#modalBody').addEventListener('click',e=>{const t=e.target.closest('button[data-go-node]');if(!t)return;closeModal();select(t.dataset.goNode)});
  $$('.lens[data-lens]').forEach(b=>b.addEventListener('click',()=>{stopMission(true);state.lens=b.dataset.lens;state.highlightPath=[];renderMap();renderInspector()}));
  $('#moreLens').addEventListener('click',()=>{$('#modalTitle').textContent='More lenses';$('#modalBody').innerHTML=`<div class="chips">${['software','performance','cost','learning'].map(id=>`<button class="lens" data-more="${id}">${lensDefs[id].label}</button>`).join('')}</div>`;openModal();$$('[data-more]').forEach(b=>b.addEventListener('click',()=>{stopMission(true);state.lens=b.dataset.more;closeModal();renderMap();renderInspector()}))});
  $('#modalClose').addEventListener('click',closeModal);$('#overlay').addEventListener('click',e=>{if(e.target===$('#overlay'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#overlay').classList.contains('open'))closeModal();else if(!$('#tutorial').classList.contains('hidden'))$('#tutorial').classList.add('hidden')}});
  $('#missionPlay').addEventListener('click',playMission);missions.forEach(m=>{const o=document.createElement('option');o.value=m.id;o.textContent=m.name;$('#missionSelect').appendChild(o)});setMissionButton(false);
  let ti=0;const tsteps=$$('.tstep');
  function renderTutorial(){tsteps.forEach((s,i)=>s.classList.toggle('active',i===ti));$('#tCount').textContent=`${ti+1} / ${tsteps.length}`;$('#tNext').textContent=ti===tsteps.length-1?'Enter Atlas →':'Next →'}
  function closeTutorial(){ $('#tutorial').classList.add('hidden'); }
  function nextTutorial(){ if(ti===tsteps.length-1){closeTutorial();return} ti++;renderTutorial(); }
  function tapSafe(el,fn){let lastTouch=0;el.addEventListener('touchend',e=>{lastTouch=Date.now();e.preventDefault();fn(e)},{passive:false});el.addEventListener('click',e=>{if(Date.now()-lastTouch<650)return;fn(e)});}
  tapSafe($('#tNext'),nextTutorial);tapSafe($('#tSkip'),closeTutorial);tapSafe($('#helpBtn'),()=>{ti=0;renderTutorial();$('#tutorial').classList.remove('hidden')});
  $('.ins-head').addEventListener('click',()=>{if(innerWidth<900)inspector.classList.toggle('open')});
  renderMini();renderMap();renderWelcome();window.__atlasReady=true;
})();
